var dibujo , lienzo ;
var xpro = 425;//ubicacion en x del bloque amarillo.
var ypro = 200;//ubicacion en y del bloque amarillo.
var vel = 5;
var modo = true;
var almas = 5;
var score = 0;
var tecla = {
    w: 119,
    a: 97,
    s: 115,
    d: 100,
    e: 101,
    spc: 32,
};
function inicio() {
    dibujo = document.getElementById("canvas");
    lienzo = dibujo.getContext("2d");
    document.addEventListener("keydown", presentacion );
    presentacion();
//    draw();
//    loop();
}
/*
function teclado (datos){
    var tips = datos.keycode;
    if ( tips == 119){
	loop();
    }
}*/
function presentacion(espacio) { //explicacion del juego
    lienzo.fillStyle="rgb(0,0,0)";//fondo
    lienzo.fillRect(0,0,900,500);
    lienzo.fillStyle="rgb(255,255,255)";
    lienzo.font="50px Arial";
    lienzo.fillText("presiona espacio para jugar",150,50);
    lienzo.font="30px Arial";
    lienzo.fillText("genera puntos",375,150);
    lienzo.fillText("quita puntos",375,200);
    lienzo.fillText("genera almas",375,250);
    lienzo.font="10px Arial";
    lienzo.fillText("los bordes empujan",410,300);
    lienzo.font="40px Arial";
    lienzo.fillText("#ByProduccionesTipson",460,480);//#Hashtag
    //dibujar colores:
    lienzo.fillStyle="rgb(0,250,0)";
    lienzo.fillRect(345,135,20,20);
    lienzo.fillStyle="rgb(250,0,0)";
    lienzo.fillRect(345,185,20,20);
    lienzo.fillStyle="rgb(250,250,250)";
    lienzo.fillRect(345,235,20,20);
    lienzo.stroke();
    var tips = espacio.keycode;
    if ( tips == 32) {
	loop();
    }
}
var miny=10;var maxy=450;var minx=900;var maxx=209000;
//var miny=10;var maxy=450;var minx=1;var maxx=900;
var minanch=10;var maxanch=70;var minh=10; var maxh=70;
// crear las variables Random de cada cuadrado (prepare your anus)
//puntos:
var p1x= Math.random()*(maxx-minx);var p1y=Math.random()*(maxy-miny);
var p1anch=Math.random()*(maxanch-minanch);var p1h=Math.random()*(maxh-minh);
var p2x=Math.random()*(maxx-minx);var p2y=Math.random()*(maxy-miny);
var p2anch=Math.random()*(maxanch-minanch);var p2h=Math.random()*(maxh-minh);
var p3x= Math.random()*(maxx-minx);var p3y=Math.random()*(maxy-miny);
var p3anch=Math.random()*(maxanch-minanch);var p3h=Math.random()*(maxh-minh);
var p4x= Math.random()*(maxx-minx);var p4y=Math.random()*(maxy-miny);
var p4anch=Math.random()*(maxanch-minanch);var p4h=Math.random()*(maxh-minh);
var p5x=Math.random()*(maxx-minx);var p5y=Math.random()*(maxy-miny);
var p5anch=Math.random()*(maxanch-minanch);var p5h=Math.random()*(maxh-minh);
var p6x=Math.random()*(maxx-minx);var p6y=Math.random()*(maxy-miny);
var p6anch=Math.random()*(maxanch-minanch);var p6h=Math.random()*(maxh-minh);
var p7x=Math.random()*(maxx-minx);var p7y=Math.random()*(maxy-miny);
var p7anch=Math.random()*(maxanch-minanch);var p7h=Math.random()*(maxh-minh);
var p8x=Math.random()*(maxx-minx);var p8y=Math.random()*(maxy-miny);
var p8anch=Math.random()*(maxanch-minanch);var p8h=Math.random()*(maxh-minh);
var p9x=Math.random()*(maxx-minx);var p9y=Math.random()*(maxy-miny);
var p9anch=Math.random()*(maxanch-minanch);var p9h=Math.random()*(maxh-minh);
var p10x=Math.random()*(maxx-minx);var p10y=Math.random()*(maxy-miny);
var p10anch=Math.random()*(maxanch-minanch);var p10h=Math.random()*(maxh-minh);
var p11x=Math.random()*(maxx-minx);var p11y=Math.random()*(maxy-miny);
var p11anch=Math.random()*(maxanch-minanch);var p11h=Math.random()*(maxh-minh);
var p12x=Math.random()*(maxx-minx);var p12y=Math.random()*(maxy-miny);
var p12anch=Math.random()*(maxanch-minanch);var p12h=Math.random()*(maxh-minh);
var p13x=Math.random()*(maxx-minx);var p13y=Math.random()*(maxy-miny);
var p13anch=Math.random()*(maxanch-minanch);var p13h=Math.random()*(maxh-minh);
var p14x=Math.random()*(maxx-minx);var p14y=Math.random()*(maxy-miny);
var p14anch=Math.random()*(maxanch-minanch);var p14h=Math.random()*(maxh-minh);
var p15x=Math.random()*(maxx-minx);var p15y=Math.random()*(maxy-miny);
var p15anch=Math.random()*(maxanch-minanch);var p15h=Math.random()*(maxh-minh);
var p16x=Math.random()*(maxx-minx);var p16y=Math.random()*(maxy-miny);
var p16anch=Math.random()*(maxanch-minanch);var p16h=Math.random()*(maxh-minh);
var p17x=Math.random()*(maxx-minx);var p17y=Math.random()*(maxy-miny);
var p17anch=Math.random()*(maxanch-minanch);var p17h=Math.random()*(maxh-minh);
var p18x=Math.random()*(maxx-minx);var p18y=Math.random()*(maxy-miny);
var p18anch=Math.random()*(maxanch-minanch);var p18h=Math.random()*(maxh-minh);
var p19x=Math.random()*(maxx-minx);var p19y=Math.random()*(maxy-miny);
var p19anch=Math.random()*(maxanch-minanch);var p19h=Math.random()*(maxh-minh);
var p20x=Math.random()*(maxx-minx);var p20y=Math.random()*(maxy-miny);
var p20anch=Math.random()*(maxanch-minanch);var p20h=Math.random()*(maxh-minh);
var p21x=Math.random()*(maxx-minx);var p21y=Math.random()*(maxy-miny);
var p21anch=Math.random()*(maxanch-minanch);var p21h=Math.random()*(maxh-minh);
var p22x=Math.random()*(maxx-minx);var p22y=Math.random()*(maxy-miny);
var p22anch=Math.random()*(maxanch-minanch);var p22h=Math.random()*(maxh-minh);
var p23x=Math.random()*(maxx-minx);var p23y=Math.random()*(maxy-miny);
var p23anch=Math.random()*(maxanch-minanch);var p23h=Math.random()*(maxh-minh);
var p24x=Math.random()*(maxx-minx);var p24y=Math.random()*(maxy-miny);
var p24anch=Math.random()*(maxanch-minanch);var p24h=Math.random()*(maxh-minh);
var p25x=Math.random()*(maxx-minx);var p25y=Math.random()*(maxy-miny);
var p25anch=Math.random()*(maxanch-minanch);var p25h=Math.random()*(maxh-minh);
var p26x=Math.random()*(maxx-minx);var p26y=Math.random()*(maxy-miny);
var p26anch=Math.random()*(maxanch-minanch);var p26h=Math.random()*(maxh-minh);
var p27x=Math.random()*(maxx-minx);var p27y=Math.random()*(maxy-miny);
var p27anch=Math.random()*(maxanch-minanch);var p27h=Math.random()*(maxh-minh);
var p28x=Math.random()*(maxx-minx);var p28y=Math.random()*(maxy-miny);
var p28anch=Math.random()*(maxanch-minanch);var p28h=Math.random()*(maxh-minh);
var p29x=Math.random()*(maxx-minx);var p29y=Math.random()*(maxy-miny);
var p29anch=Math.random()*(maxanch-minanch);var p29h=Math.random()*(maxh-minh);
var p30x=Math.random()*(maxx-minx);var p30y=Math.random()*(maxy-miny);
var p30anch=Math.random()*(maxanch-minanch);var p30h=Math.random()*(maxh-minh);
var p31x=Math.random()*(maxx-minx);var p31y=Math.random()*(maxy-miny);
var p31anch=Math.random()*(maxanch-minanch);var p31h=Math.random()*(maxh-minh);
var p32x=Math.random()*(maxx-minx);var p32y=Math.random()*(maxy-miny);
var p32anch=Math.random()*(maxanch-minanch);var p32h=Math.random()*(maxh-minh);
var p33x=Math.random()*(maxx-minx);var p33y=Math.random()*(maxy-miny);
var p33anch=Math.random()*(maxanch-minanch);var p33h=Math.random()*(maxh-minh);
var p34x=Math.random()*(maxx-minx);var p34y=Math.random()*(maxy-miny);
var p34anch=Math.random()*(maxanch-minanch);var p34h=Math.random()*(maxh-minh);
var p35x=Math.random()*(maxx-minx);var p35y=Math.random()*(maxy-miny);
var p35anch=Math.random()*(maxanch-minanch);var p35h=Math.random()*(maxh-minh);
var p36x=Math.random()*(maxx-minx);var p36y=Math.random()*(maxy-miny);
var p36anch=Math.random()*(maxanch-minanch);var p36h=Math.random()*(maxh-minh);
var p37x=Math.random()*(maxx-minx);var p37y=Math.random()*(maxy-miny);
var p37anch=Math.random()*(maxanch-minanch);var p37h=Math.random()*(maxh-minh);
var p38x=Math.random()*(maxx-minx);var p38y=Math.random()*(maxy-miny);
var p38anch=Math.random()*(maxanch-minanch);var p38h=Math.random()*(maxh-minh);
var p39x=Math.random()*(maxx-minx);var p39y=Math.random()*(maxy-miny);
var p39anch=Math.random()*(maxanch-minanch);var p39h=Math.random()*(maxh-minh);
var p40x=Math.random()*(maxx-minx);var p40y=Math.random()*(maxy-miny);
var p40anch=Math.random()*(maxanch-minanch);var p40h=Math.random()*(maxh-minh);
var p41x=Math.random()*(maxx-minx);var p41y=Math.random()*(maxy-miny);
var p41anch=Math.random()*(maxanch-minanch);var p41h=Math.random()*(maxh-minh);
var p42x=Math.random()*(maxx-minx);var p42y=Math.random()*(maxy-miny);
var p42anch=Math.random()*(maxanch-minanch);var p42h=Math.random()*(maxh-minh);
var p43x=Math.random()*(maxx-minx);var p43y=Math.random()*(maxy-miny);
var p43anch=Math.random()*(maxanch-minanch);var p43h=Math.random()*(maxh-minh);
var p44x=Math.random()*(maxx-minx);var p44y=Math.random()*(maxy-miny);
var p44anch=Math.random()*(maxanch-minanch);var p44h=Math.random()*(maxh-minh);
var p45x=Math.random()*(maxx-minx);var p45y=Math.random()*(maxy-miny);
var p45anch=Math.random()*(maxanch-minanch);var p45h=Math.random()*(maxh-minh);
var p46x=Math.random()*(maxx-minx);var p46y=Math.random()*(maxy-miny);
var p46anch=Math.random()*(maxanch-minanch);var p46h=Math.random()*(maxh-minh);
var p47x=Math.random()*(maxx-minx);var p47y=Math.random()*(maxy-miny);
var p47anch=Math.random()*(maxanch-minanch);var p47h=Math.random()*(maxh-minh);
var p48x=Math.random()*(maxx-minx);var p48y=Math.random()*(maxy-miny);
var p48anch=Math.random()*(maxanch-minanch);var p48h=Math.random()*(maxh-minh);
var p49x=Math.random()*(maxx-minx);var p49y=Math.random()*(maxy-miny);
var p49anch=Math.random()*(maxanch-minanch);var p49h=Math.random()*(maxh-minh);
var p50x=Math.random()*(maxx-minx);var p50y=Math.random()*(maxy-miny);
var p50anch=Math.random()*(maxanch-minanch);var p50h=Math.random()*(maxh-minh);
var p51x=Math.random()*(maxx-minx);var p51y=Math.random()*(maxy-miny);
var p51anch=Math.random()*(maxanch-minanch);var p51h=Math.random()*(maxh-minh);
var p52x=Math.random()*(maxx-minx);var p52y=Math.random()*(maxy-miny);
var p52anch=Math.random()*(maxanch-minanch);var p52h=Math.random()*(maxh-minh);
var p53x=Math.random()*(maxx-minx);var p53y=Math.random()*(maxy-miny);
var p53anch=Math.random()*(maxanch-minanch);var p53h=Math.random()*(maxh-minh);
var p54x=Math.random()*(maxx-minx);var p54y=Math.random()*(maxy-miny);
var p54anch=Math.random()*(maxanch-minanch);var p54h=Math.random()*(maxh-minh);
var p55x=Math.random()*(maxx-minx);var p55y=Math.random()*(maxy-miny);
var p55anch=Math.random()*(maxanch-minanch);var p55h=Math.random()*(maxh-minh);
var p56x=Math.random()*(maxx-minx);var p56y=Math.random()*(maxy-miny);
var p56anch=Math.random()*(maxanch-minanch);var p56h=Math.random()*(maxh-minh);
var p57x=Math.random()*(maxx-minx);var p57y=Math.random()*(maxy-miny);
var p57anch=Math.random()*(maxanch-minanch);var p57h=Math.random()*(maxh-minh);
var p58x=Math.random()*(maxx-minx);var p58y=Math.random()*(maxy-miny);
var p58anch=Math.random()*(maxanch-minanch);var p58h=Math.random()*(maxh-minh);
var p59x=Math.random()*(maxx-minx);var p59y=Math.random()*(maxy-miny);
var p59anch=Math.random()*(maxanch-minanch);var p59h=Math.random()*(maxh-minh);
var p60x=Math.random()*(maxx-minx);var p60y=Math.random()*(maxy-miny);
var p60anch=Math.random()*(maxanch-minanch);var p60h=Math.random()*(maxh-minh);
var p61x=Math.random()*(maxx-minx);var p61y=Math.random()*(maxy-miny);
var p61anch=Math.random()*(maxanch-minanch);var p61h=Math.random()*(maxh-minh);
var p62x=Math.random()*(maxx-minx);var p62y=Math.random()*(maxy-miny);
var p62anch=Math.random()*(maxanch-minanch);var p62h=Math.random()*(maxh-minh);
var p63x=Math.random()*(maxx-minx);var p63y=Math.random()*(maxy-miny);
var p63anch=Math.random()*(maxanch-minanch);var p63h=Math.random()*(maxh-minh);
var p64x=Math.random()*(maxx-minx);var p64y=Math.random()*(maxy-miny);
var p64anch=Math.random()*(maxanch-minanch);var p64h=Math.random()*(maxh-minh);
var p65x=Math.random()*(maxx-minx);var p65y=Math.random()*(maxy-miny);
var p65anch=Math.random()*(maxanch-minanch);var p65h=Math.random()*(maxh-minh);
var p66x=Math.random()*(maxx-minx);var p66y=Math.random()*(maxy-miny);
var p66anch=Math.random()*(maxanch-minanch);var p66h=Math.random()*(maxh-minh);
var p67x=Math.random()*(maxx-minx);var p67y=Math.random()*(maxy-miny);
var p67anch=Math.random()*(maxanch-minanch);var p67h=Math.random()*(maxh-minh);
var p68x=Math.random()*(maxx-minx);var p68y=Math.random()*(maxy-miny);
var p68anch=Math.random()*(maxanch-minanch);var p68h=Math.random()*(maxh-minh);
var p69x=Math.random()*(maxx-minx);var p69y=Math.random()*(maxy-miny);
var p69anch=Math.random()*(maxanch-minanch);var p69h=Math.random()*(maxh-minh);
var p70x=Math.random()*(maxx-minx);var p70y=Math.random()*(maxy-miny);
var p70anch=Math.random()*(maxanch-minanch);var p70h=Math.random()*(maxh-minh);
var p71x=Math.random()*(maxx-minx);var p71y=Math.random()*(maxy-miny);
var p71anch=Math.random()*(maxanch-minanch);var p71h=Math.random()*(maxh-minh);
var p72x=Math.random()*(maxx-minx);var p72y=Math.random()*(maxy-miny);
var p72anch=Math.random()*(maxanch-minanch);var p72h=Math.random()*(maxh-minh);
var p73x=Math.random()*(maxx-minx);var p73y=Math.random()*(maxy-miny);
var p73anch=Math.random()*(maxanch-minanch);var p73h=Math.random()*(maxh-minh);
var p74x=Math.random()*(maxx-minx);var p74y=Math.random()*(maxy-miny);
var p74anch=Math.random()*(maxanch-minanch);var p74h=Math.random()*(maxh-minh);
var p75x=Math.random()*(maxx-minx);var p75y=Math.random()*(maxy-miny);
var p75anch=Math.random()*(maxanch-minanch);var p75h=Math.random()*(maxh-minh);
var p76x=Math.random()*(maxx-minx);var p76y=Math.random()*(maxy-miny);
var p76anch=Math.random()*(maxanch-minanch);var p76h=Math.random()*(maxh-minh);
var p77x=Math.random()*(maxx-minx);var p77y=Math.random()*(maxy-miny);
var p77anch=Math.random()*(maxanch-minanch);var p77h=Math.random()*(maxh-minh);
var p78x=Math.random()*(maxx-minx);var p78y=Math.random()*(maxy-miny);
var p78anch=Math.random()*(maxanch-minanch);var p78h=Math.random()*(maxh-minh);
var p79x=Math.random()*(maxx-minx);var p79y=Math.random()*(maxy-miny);
var p79anch=Math.random()*(maxanch-minanch);var p79h=Math.random()*(maxh-minh);
var p80x=Math.random()*(maxx-minx);var p80y=Math.random()*(maxy-miny);
var p80anch=Math.random()*(maxanch-minanch);var p80h=Math.random()*(maxh-minh);
var p81x=Math.random()*(maxx-minx);var p81y=Math.random()*(maxy-miny);
var p81anch=Math.random()*(maxanch-minanch);var p81h=Math.random()*(maxh-minh);
var p82x=Math.random()*(maxx-minx);var p82y=Math.random()*(maxy-miny);
var p82anch=Math.random()*(maxanch-minanch);var p82h=Math.random()*(maxh-minh);
var p83x=Math.random()*(maxx-minx);var p83y=Math.random()*(maxy-miny);
var p83anch=Math.random()*(maxanch-minanch);var p83h=Math.random()*(maxh-minh);
var p84x=Math.random()*(maxx-minx);var p84y=Math.random()*(maxy-miny);
var p84anch=Math.random()*(maxanch-minanch);var p84h=Math.random()*(maxh-minh);
var p85x=Math.random()*(maxx-minx);var p85y=Math.random()*(maxy-miny);
var p85anch=Math.random()*(maxanch-minanch);var p85h=Math.random()*(maxh-minh);
var p86x=Math.random()*(maxx-minx);var p86y=Math.random()*(maxy-miny);
var p86anch=Math.random()*(maxanch-minanch);var p86h=Math.random()*(maxh-minh);
var p87x=Math.random()*(maxx-minx);var p87y=Math.random()*(maxy-miny);
var p87anch=Math.random()*(maxanch-minanch);var p87h=Math.random()*(maxh-minh);
var p88x=Math.random()*(maxx-minx);var p88y=Math.random()*(maxy-miny);
var p88anch=Math.random()*(maxanch-minanch);var p88h=Math.random()*(maxh-minh);
var p89x=Math.random()*(maxx-minx);var p89y=Math.random()*(maxy-miny);
var p89anch=Math.random()*(maxanch-minanch);var p89h=Math.random()*(maxh-minh);
var p90x=Math.random()*(maxx-minx);var p90y=Math.random()*(maxy-miny);
var p90anch=Math.random()*(maxanch-minanch);var p90h=Math.random()*(maxh-minh);
var p91x=Math.random()*(maxx-minx);var p91y=Math.random()*(maxy-miny);
var p91anch=Math.random()*(maxanch-minanch);var p91h=Math.random()*(maxh-minh);
var p92x=Math.random()*(maxx-minx);var p92y=Math.random()*(maxy-miny);
var p92anch=Math.random()*(maxanch-minanch);var p92h=Math.random()*(maxh-minh);
var p93x=Math.random()*(maxx-minx);var p93y=Math.random()*(maxy-miny);
var p93anch=Math.random()*(maxanch-minanch);var p93h=Math.random()*(maxh-minh);
var p94x=Math.random()*(maxx-minx);var p94y=Math.random()*(maxy-miny);
var p94anch=Math.random()*(maxanch-minanch);var p94h=Math.random()*(maxh-minh);
var p95x=Math.random()*(maxx-minx);var p95y=Math.random()*(maxy-miny);
var p95anch=Math.random()*(maxanch-minanch);var p95h=Math.random()*(maxh-minh);
var p96x=Math.random()*(maxx-minx);var p96y=Math.random()*(maxy-miny);
var p96anch=Math.random()*(maxanch-minanch);var p96h=Math.random()*(maxh-minh);
var p97x=Math.random()*(maxx-minx);var p97y=Math.random()*(maxy-miny);
var p97anch=Math.random()*(maxanch-minanch);var p97h=Math.random()*(maxh-minh);
var p98x=Math.random()*(maxx-minx);var p98y=Math.random()*(maxy-miny);
var p98anch=Math.random()*(maxanch-minanch);var p98h=Math.random()*(maxh-minh);
var p99x=Math.random()*(maxx-minx);var p99y=Math.random()*(maxy-miny);
var p99anch=Math.random()*(maxanch-minanch);var p99h=Math.random()*(maxh-minh);
var p100x=Math.random()*(maxx-minx);var p100y=Math.random()*(maxy-miny);
var p100anch=Math.random()*(maxanch-minanch);var p100h=Math.random()*(maxh-minh);
//almas:
var a1x=Math.random()*(maxx-minx);var a1y=Math.random()*(maxy-miny);
var a1anch=Math.random()*(maxanch-minanch);var a1h=Math.random()*(maxh-minh);
var a2x=Math.random()*(maxx-minx);var a2y=Math.random()*(maxy-miny);
var a2anch=Math.random()*(maxanch-minanch);var a2h=Math.random()*(maxh-minh);
var a3x=Math.random()*(maxx-minx);var a3y=Math.random()*(maxy-miny);
var a3anch=Math.random()*(maxanch-minanch);var a3h=Math.random()*(maxh-minh);
var a4x=Math.random()*(maxx-minx);var a4y=Math.random()*(maxy-miny);
var a4anch=Math.random()*(maxanch-minanch);var a4h=Math.random()*(maxh-minh);
var a5x=Math.random()*(maxx-minx);var a5y=Math.random()*(maxy-miny);
var a5anch=Math.random()*(maxanch-minanch);var a5h=Math.random()*(maxh-minh);
//obstaculos: (TRECIENTOS FUUUUUUUUUUUCKING BLOQUES !!!!!)
var o1x=Math.random()*(maxx-minx);var o1y=Math.random()*(maxy-miny);
var o1anch=Math.random()*(maxanch-minanch);var o1h=Math.random()*(maxh-minh);
var o2x=Math.random()*(maxx-minx);var o2y=Math.random()*(maxy-miny);
var o2anch=Math.random()*(maxanch-minanch);var o2h=Math.random()*(maxh-minh);
var o3x=Math.random()*(maxx-minx);var o3y=Math.random()*(maxy-miny);
var o3anch=Math.random()*(maxanch-minanch);var o3h=Math.random()*(maxh-minh);
var o4x=Math.random()*(maxx-minx);var o4y=Math.random()*(maxy-miny);
var o4anch=Math.random()*(maxanch-minanch);var o4h=Math.random()*(maxh-minh);
var o5x=Math.random()*(maxx-minx);var o5y=Math.random()*(maxy-miny);
var o5anch=Math.random()*(maxanch-minanch);var o5h=Math.random()*(maxh-minh);
var o6x=Math.random()*(maxx-minx);var o6y=Math.random()*(maxy-miny);
var o6anch=Math.random()*(maxanch-minanch);var o6h=Math.random()*(maxh-minh);
var o7x=Math.random()*(maxx-minx);var o7y=Math.random()*(maxy-miny);
var o7anch=Math.random()*(maxanch-minanch);var o7h=Math.random()*(maxh-minh);
var o8x=Math.random()*(maxx-minx);var o8y=Math.random()*(maxy-miny);
var o8anch=Math.random()*(maxanch-minanch);var o8h=Math.random()*(maxh-minh);
var o9x=Math.random()*(maxx-minx);var o9y=Math.random()*(maxy-miny);
var o9anch=Math.random()*(maxanch-minanch);var o9h=Math.random()*(maxh-minh);
var o10x=Math.random()*(maxx-minx);var o10y=Math.random()*(maxy-miny);
var o10anch=Math.random()*(maxanch-minanch);var o10h=Math.random()*(maxh-minh);
var o11x=Math.random()*(maxx-minx);var o11y=Math.random()*(maxy-miny);
var o11anch=Math.random()*(maxanch-minanch);var o11h=Math.random()*(maxh-minh);
var o12x=Math.random()*(maxx-minx);var o12y=Math.random()*(maxy-miny);
var o12anch=Math.random()*(maxanch-minanch);var o12h=Math.random()*(maxh-minh);
var o13x=Math.random()*(maxx-minx);var o13y=Math.random()*(maxy-miny);
var o13anch=Math.random()*(maxanch-minanch);var o13h=Math.random()*(maxh-minh);
var o14x=Math.random()*(maxx-minx);var o14y=Math.random()*(maxy-miny);
var o14anch=Math.random()*(maxanch-minanch);var o14h=Math.random()*(maxh-minh);
var o15x=Math.random()*(maxx-minx);var o15y=Math.random()*(maxy-miny);
var o15anch=Math.random()*(maxanch-minanch);var o15h=Math.random()*(maxh-minh);
var o16x=Math.random()*(maxx-minx);var o16y=Math.random()*(maxy-miny);
var o16anch=Math.random()*(maxanch-minanch);var o16h=Math.random()*(maxh-minh);
var o17x=Math.random()*(maxx-minx);var o17y=Math.random()*(maxy-miny);
var o17anch=Math.random()*(maxanch-minanch);var o17h=Math.random()*(maxh-minh);
var o18x=Math.random()*(maxx-minx);var o18y=Math.random()*(maxy-miny);
var o18anch=Math.random()*(maxanch-minanch);var o18h=Math.random()*(maxh-minh);
var o19x=Math.random()*(maxx-minx);var o19y=Math.random()*(maxy-miny);
var o19anch=Math.random()*(maxanch-minanch);var o19h=Math.random()*(maxh-minh);
var o20x=Math.random()*(maxx-minx);var o20y=Math.random()*(maxy-miny);
var o20anch=Math.random()*(maxanch-minanch);var o20h=Math.random()*(maxh-minh);
var o21x=Math.random()*(maxx-minx);var o21y=Math.random()*(maxy-miny);
var o21anch=Math.random()*(maxanch-minanch);var o21h=Math.random()*(maxh-minh);
var o22x=Math.random()*(maxx-minx);var o22y=Math.random()*(maxy-miny);
var o22anch=Math.random()*(maxanch-minanch);var o22h=Math.random()*(maxh-minh);
var o23x=Math.random()*(maxx-minx);var o23y=Math.random()*(maxy-miny);
var o23anch=Math.random()*(maxanch-minanch);var o23h=Math.random()*(maxh-minh);
var o24x=Math.random()*(maxx-minx);var o24y=Math.random()*(maxy-miny);
var o24anch=Math.random()*(maxanch-minanch);var o24h=Math.random()*(maxh-minh);
var o25x=Math.random()*(maxx-minx);var o25y=Math.random()*(maxy-miny);
var o25anch=Math.random()*(maxanch-minanch);var o25h=Math.random()*(maxh-minh);
var o26x=Math.random()*(maxx-minx);var o26y=Math.random()*(maxy-miny);
var o26anch=Math.random()*(maxanch-minanch);var o26h=Math.random()*(maxh-minh);
var o27x=Math.random()*(maxx-minx);var o27y=Math.random()*(maxy-miny);
var o27anch=Math.random()*(maxanch-minanch);var o27h=Math.random()*(maxh-minh);
var o28x=Math.random()*(maxx-minx);var o28y=Math.random()*(maxy-miny);
var o28anch=Math.random()*(maxanch-minanch);var o28h=Math.random()*(maxh-minh);
var o29x=Math.random()*(maxx-minx);var o29y=Math.random()*(maxy-miny);
var o29anch=Math.random()*(maxanch-minanch);var o29h=Math.random()*(maxh-minh);
var o30x=Math.random()*(maxx-minx);var o30y=Math.random()*(maxy-miny);
var o30anch=Math.random()*(maxanch-minanch);var o30h=Math.random()*(maxh-minh);
var o31x=Math.random()*(maxx-minx);var o31y=Math.random()*(maxy-miny);
var o31anch=Math.random()*(maxanch-minanch);var o31h=Math.random()*(maxh-minh);
var o32x=Math.random()*(maxx-minx);var o32y=Math.random()*(maxy-miny);
var o32anch=Math.random()*(maxanch-minanch);var o32h=Math.random()*(maxh-minh);
var o33x=Math.random()*(maxx-minx);var o33y=Math.random()*(maxy-miny);
var o33anch=Math.random()*(maxanch-minanch);var o33h=Math.random()*(maxh-minh);
var o34x=Math.random()*(maxx-minx);var o34y=Math.random()*(maxy-miny);
var o34anch=Math.random()*(maxanch-minanch);var o34h=Math.random()*(maxh-minh);
var o35x=Math.random()*(maxx-minx);var o35y=Math.random()*(maxy-miny);
var o35anch=Math.random()*(maxanch-minanch);var o35h=Math.random()*(maxh-minh);
var o36x=Math.random()*(maxx-minx);var o36y=Math.random()*(maxy-miny);
var o36anch=Math.random()*(maxanch-minanch);var o36h=Math.random()*(maxh-minh);
var o37x=Math.random()*(maxx-minx);var o37y=Math.random()*(maxy-miny);
var o37anch=Math.random()*(maxanch-minanch);var o37h=Math.random()*(maxh-minh);
var o38x=Math.random()*(maxx-minx);var o38y=Math.random()*(maxy-miny);
var o38anch=Math.random()*(maxanch-minanch);var o38h=Math.random()*(maxh-minh);
var o39x=Math.random()*(maxx-minx);var o39y=Math.random()*(maxy-miny);
var o39anch=Math.random()*(maxanch-minanch);var o39h=Math.random()*(maxh-minh);
var o40x=Math.random()*(maxx-minx);var o40y=Math.random()*(maxy-miny);
var o40anch=Math.random()*(maxanch-minanch);var o40h=Math.random()*(maxh-minh);
var o41x=Math.random()*(maxx-minx);var o41y=Math.random()*(maxy-miny);
var o41anch=Math.random()*(maxanch-minanch);var o41h=Math.random()*(maxh-minh);
var o42x=Math.random()*(maxx-minx);var o42y=Math.random()*(maxy-miny);
var o42anch=Math.random()*(maxanch-minanch);var o42h=Math.random()*(maxh-minh);
var o43x=Math.random()*(maxx-minx);var o43y=Math.random()*(maxy-miny);
var o43anch=Math.random()*(maxanch-minanch);var o43h=Math.random()*(maxh-minh);
var o44x=Math.random()*(maxx-minx);var o44y=Math.random()*(maxy-miny);
var o44anch=Math.random()*(maxanch-minanch);var o44h=Math.random()*(maxh-minh);
var o45x=Math.random()*(maxx-minx);var o45y=Math.random()*(maxy-miny);
var o45anch=Math.random()*(maxanch-minanch);var o45h=Math.random()*(maxh-minh);
var o46x=Math.random()*(maxx-minx);var o46y=Math.random()*(maxy-miny);
var o46anch=Math.random()*(maxanch-minanch);var o46h=Math.random()*(maxh-minh);
var o47x=Math.random()*(maxx-minx);var o47y=Math.random()*(maxy-miny);
var o47anch=Math.random()*(maxanch-minanch);var o47h=Math.random()*(maxh-minh);
var o48x=Math.random()*(maxx-minx);var o48y=Math.random()*(maxy-miny);
var o48anch=Math.random()*(maxanch-minanch);var o48h=Math.random()*(maxh-minh);
var o49x=Math.random()*(maxx-minx);var o49y=Math.random()*(maxy-miny);
var o49anch=Math.random()*(maxanch-minanch);var o49h=Math.random()*(maxh-minh);
var o50x=Math.random()*(maxx-minx);var o50y=Math.random()*(maxy-miny);
var o50anch=Math.random()*(maxanch-minanch);var o50h=Math.random()*(maxh-minh);
var o51x=Math.random()*(maxx-minx);var o51y=Math.random()*(maxy-miny);
var o51anch=Math.random()*(maxanch-minanch);var o51h=Math.random()*(maxh-minh);
var o52x=Math.random()*(maxx-minx);var o52y=Math.random()*(maxy-miny);
var o52anch=Math.random()*(maxanch-minanch);var o52h=Math.random()*(maxh-minh);
var o53x=Math.random()*(maxx-minx);var o53y=Math.random()*(maxy-miny);
var o53anch=Math.random()*(maxanch-minanch);var o53h=Math.random()*(maxh-minh);
var o54x=Math.random()*(maxx-minx);var o54y=Math.random()*(maxy-miny);
var o54anch=Math.random()*(maxanch-minanch);var o54h=Math.random()*(maxh-minh);
var o55x=Math.random()*(maxx-minx);var o55y=Math.random()*(maxy-miny);
var o55anch=Math.random()*(maxanch-minanch);var o55h=Math.random()*(maxh-minh);
var o56x=Math.random()*(maxx-minx);var o56y=Math.random()*(maxy-miny);
var o56anch=Math.random()*(maxanch-minanch);var o56h=Math.random()*(maxh-minh);
var o57x=Math.random()*(maxx-minx);var o57y=Math.random()*(maxy-miny);
var o57anch=Math.random()*(maxanch-minanch);var o57h=Math.random()*(maxh-minh);
var o58x=Math.random()*(maxx-minx);var o58y=Math.random()*(maxy-miny);
var o58anch=Math.random()*(maxanch-minanch);var o58h=Math.random()*(maxh-minh);
var o59x=Math.random()*(maxx-minx);var o59y=Math.random()*(maxy-miny);
var o59anch=Math.random()*(maxanch-minanch);var o59h=Math.random()*(maxh-minh);
var o60x=Math.random()*(maxx-minx);var o60y=Math.random()*(maxy-miny);
var o60anch=Math.random()*(maxanch-minanch);var o60h=Math.random()*(maxh-minh);
var o61x=Math.random()*(maxx-minx);var o61y=Math.random()*(maxy-miny);
var o61anch=Math.random()*(maxanch-minanch);var o61h=Math.random()*(maxh-minh);
var o62x=Math.random()*(maxx-minx);var o62y=Math.random()*(maxy-miny);
var o62anch=Math.random()*(maxanch-minanch);var o62h=Math.random()*(maxh-minh);
var o63x=Math.random()*(maxx-minx);var o63y=Math.random()*(maxy-miny);
var o63anch=Math.random()*(maxanch-minanch);var o63h=Math.random()*(maxh-minh);
var o64x=Math.random()*(maxx-minx);var o64y=Math.random()*(maxy-miny);
var o64anch=Math.random()*(maxanch-minanch);var o64h=Math.random()*(maxh-minh);
var o65x=Math.random()*(maxx-minx);var o65y=Math.random()*(maxy-miny);
var o65anch=Math.random()*(maxanch-minanch);var o65h=Math.random()*(maxh-minh);
var o66x=Math.random()*(maxx-minx);var o66y=Math.random()*(maxy-miny);
var o66anch=Math.random()*(maxanch-minanch);var o66h=Math.random()*(maxh-minh);
var o67x=Math.random()*(maxx-minx);var o67y=Math.random()*(maxy-miny);
var o67anch=Math.random()*(maxanch-minanch);var o67h=Math.random()*(maxh-minh);
var o68x=Math.random()*(maxx-minx);var o68y=Math.random()*(maxy-miny);
var o68anch=Math.random()*(maxanch-minanch);var o68h=Math.random()*(maxh-minh);
var o69x=Math.random()*(maxx-minx);var o69y=Math.random()*(maxy-miny);
var o69anch=Math.random()*(maxanch-minanch);var o69h=Math.random()*(maxh-minh);
var o70x=Math.random()*(maxx-minx);var o70y=Math.random()*(maxy-miny);
var o70anch=Math.random()*(maxanch-minanch);var o70h=Math.random()*(maxh-minh);
var o71x=Math.random()*(maxx-minx);var o71y=Math.random()*(maxy-miny);
var o71anch=Math.random()*(maxanch-minanch);var o71h=Math.random()*(maxh-minh);
var o72x=Math.random()*(maxx-minx);var o72y=Math.random()*(maxy-miny);
var o72anch=Math.random()*(maxanch-minanch);var o72h=Math.random()*(maxh-minh);
var o73x=Math.random()*(maxx-minx);var o73y=Math.random()*(maxy-miny);
var o73anch=Math.random()*(maxanch-minanch);var o73h=Math.random()*(maxh-minh);
var o74x=Math.random()*(maxx-minx);var o74y=Math.random()*(maxy-miny);
var o74anch=Math.random()*(maxanch-minanch);var o74h=Math.random()*(maxh-minh);
var o75x=Math.random()*(maxx-minx);var o75y=Math.random()*(maxy-miny);
var o75anch=Math.random()*(maxanch-minanch);var o75h=Math.random()*(maxh-minh);
var o76x=Math.random()*(maxx-minx);var o76y=Math.random()*(maxy-miny);
var o76anch=Math.random()*(maxanch-minanch);var o76h=Math.random()*(maxh-minh);
var o77x=Math.random()*(maxx-minx);var o77y=Math.random()*(maxy-miny);
var o77anch=Math.random()*(maxanch-minanch);var o77h=Math.random()*(maxh-minh);
var o78x=Math.random()*(maxx-minx);var o78y=Math.random()*(maxy-miny);
var o78anch=Math.random()*(maxanch-minanch);var o78h=Math.random()*(maxh-minh);
var o79x=Math.random()*(maxx-minx);var o79y=Math.random()*(maxy-miny);
var o79anch=Math.random()*(maxanch-minanch);var o79h=Math.random()*(maxh-minh);
var o80x=Math.random()*(maxx-minx);var o80y=Math.random()*(maxy-miny);
var o80anch=Math.random()*(maxanch-minanch);var o80h=Math.random()*(maxh-minh);
var o81x=Math.random()*(maxx-minx);var o81y=Math.random()*(maxy-miny);
var o81anch=Math.random()*(maxanch-minanch);var o81h=Math.random()*(maxh-minh);
var o82x=Math.random()*(maxx-minx);var o82y=Math.random()*(maxy-miny);
var o82anch=Math.random()*(maxanch-minanch);var o82h=Math.random()*(maxh-minh);
var o83x=Math.random()*(maxx-minx);var o83y=Math.random()*(maxy-miny);
var o83anch=Math.random()*(maxanch-minanch);var o83h=Math.random()*(maxh-minh);
var o84x=Math.random()*(maxx-minx);var o84y=Math.random()*(maxy-miny);
var o84anch=Math.random()*(maxanch-minanch);var o84h=Math.random()*(maxh-minh);
var o85x=Math.random()*(maxx-minx);var o85y=Math.random()*(maxy-miny);
var o85anch=Math.random()*(maxanch-minanch);var o85h=Math.random()*(maxh-minh);
var o86x=Math.random()*(maxx-minx);var o86y=Math.random()*(maxy-miny);
var o86anch=Math.random()*(maxanch-minanch);var o86h=Math.random()*(maxh-minh);
var o87x=Math.random()*(maxx-minx);var o87y=Math.random()*(maxy-miny);
var o87anch=Math.random()*(maxanch-minanch);var o87h=Math.random()*(maxh-minh);
var o88x=Math.random()*(maxx-minx);var o88y=Math.random()*(maxy-miny);
var o88anch=Math.random()*(maxanch-minanch);var o88h=Math.random()*(maxh-minh);
var o89x=Math.random()*(maxx-minx);var o89y=Math.random()*(maxy-miny);
var o89anch=Math.random()*(maxanch-minanch);var o89h=Math.random()*(maxh-minh);
var o90x=Math.random()*(maxx-minx);var o90y=Math.random()*(maxy-miny);
var o90anch=Math.random()*(maxanch-minanch);var o90h=Math.random()*(maxh-minh);
var o91x=Math.random()*(maxx-minx);var o91y=Math.random()*(maxy-miny);
var o91anch=Math.random()*(maxanch-minanch);var o91h=Math.random()*(maxh-minh);
var o92x=Math.random()*(maxx-minx);var o92y=Math.random()*(maxy-miny);
var o92anch=Math.random()*(maxanch-minanch);var o92h=Math.random()*(maxh-minh);
var o93x=Math.random()*(maxx-minx);var o93y=Math.random()*(maxy-miny);
var o93anch=Math.random()*(maxanch-minanch);var o93h=Math.random()*(maxh-minh);
var o94x=Math.random()*(maxx-minx);var o94y=Math.random()*(maxy-miny);
var o94anch=Math.random()*(maxanch-minanch);var o94h=Math.random()*(maxh-minh);
var o95x=Math.random()*(maxx-minx);var o95y=Math.random()*(maxy-miny);
var o95anch=Math.random()*(maxanch-minanch);var o95h=Math.random()*(maxh-minh);
var o96x=Math.random()*(maxx-minx);var o96y=Math.random()*(maxy-miny);
var o96anch=Math.random()*(maxanch-minanch);var o96h=Math.random()*(maxh-minh);
var o97x=Math.random()*(maxx-minx);var o97y=Math.random()*(maxy-miny);
var o97anch=Math.random()*(maxanch-minanch);var o97h=Math.random()*(maxh-minh);
var o98x=Math.random()*(maxx-minx);var o98y=Math.random()*(maxy-miny);
var o98anch=Math.random()*(maxanch-minanch);var o98h=Math.random()*(maxh-minh);
var o99x=Math.random()*(maxx-minx);var o99y=Math.random()*(maxy-miny);
var o99anch=Math.random()*(maxanch-minanch);var o99h=Math.random()*(maxh-minh);
var o100x=Math.random()*(maxx-minx);var o100y=Math.random()*(maxy-miny);
var o100anch=Math.random()*(maxanch-minanch);var o100h=Math.random()*(maxh-minh);
var o101x=Math.random()*(maxx-minx);var o101y=Math.random()*(maxy-miny);
var o101anch=Math.random()*(maxanch-minanch);var o101h=Math.random()*(maxh-minh);
var o102x=Math.random()*(maxx-minx);var o102y=Math.random()*(maxy-miny);
var o102anch=Math.random()*(maxanch-minanch);var o102h=Math.random()*(maxh-minh);
var o103x=Math.random()*(maxx-minx);var o103y=Math.random()*(maxy-miny);
var o103anch=Math.random()*(maxanch-minanch);var o103h=Math.random()*(maxh-minh);
var o104x=Math.random()*(maxx-minx);var o104y=Math.random()*(maxy-miny);
var o104anch=Math.random()*(maxanch-minanch);var o104h=Math.random()*(maxh-minh);
var o105x=Math.random()*(maxx-minx);var o105y=Math.random()*(maxy-miny);
var o105anch=Math.random()*(maxanch-minanch);var o105h=Math.random()*(maxh-minh);
var o106x=Math.random()*(maxx-minx);var o106y=Math.random()*(maxy-miny);
var o106anch=Math.random()*(maxanch-minanch);var o106h=Math.random()*(maxh-minh);
var o107x=Math.random()*(maxx-minx);var o107y=Math.random()*(maxy-miny);
var o107anch=Math.random()*(maxanch-minanch);var o107h=Math.random()*(maxh-minh);
var o108x=Math.random()*(maxx-minx);var o108y=Math.random()*(maxy-miny);
var o108anch=Math.random()*(maxanch-minanch);var o108h=Math.random()*(maxh-minh);
var o109x=Math.random()*(maxx-minx);var o109y=Math.random()*(maxy-miny);
var o109anch=Math.random()*(maxanch-minanch);var o109h=Math.random()*(maxh-minh);
var o110x=Math.random()*(maxx-minx);var o110y=Math.random()*(maxy-miny);
var o110anch=Math.random()*(maxanch-minanch);var o110h=Math.random()*(maxh-minh);
var o111x=Math.random()*(maxx-minx);var o111y=Math.random()*(maxy-miny);
var o111anch=Math.random()*(maxanch-minanch);var o111h=Math.random()*(maxh-minh);
var o112x=Math.random()*(maxx-minx);var o112y=Math.random()*(maxy-miny);
var o112anch=Math.random()*(maxanch-minanch);var o112h=Math.random()*(maxh-minh);
var o113x=Math.random()*(maxx-minx);var o113y=Math.random()*(maxy-miny);
var o113anch=Math.random()*(maxanch-minanch);var o113h=Math.random()*(maxh-minh);
var o114x=Math.random()*(maxx-minx);var o114y=Math.random()*(maxy-miny);
var o114anch=Math.random()*(maxanch-minanch);var o114h=Math.random()*(maxh-minh);
var o115x=Math.random()*(maxx-minx);var o115y=Math.random()*(maxy-miny);
var o115anch=Math.random()*(maxanch-minanch);var o115h=Math.random()*(maxh-minh);
var o116x=Math.random()*(maxx-minx);var o116y=Math.random()*(maxy-miny);
var o116anch=Math.random()*(maxanch-minanch);var o116h=Math.random()*(maxh-minh);
var o117x=Math.random()*(maxx-minx);var o117y=Math.random()*(maxy-miny);
var o117anch=Math.random()*(maxanch-minanch);var o117h=Math.random()*(maxh-minh);
var o118x=Math.random()*(maxx-minx);var o118y=Math.random()*(maxy-miny);
var o118anch=Math.random()*(maxanch-minanch);var o118h=Math.random()*(maxh-minh);
var o119x=Math.random()*(maxx-minx);var o119y=Math.random()*(maxy-miny);
var o119anch=Math.random()*(maxanch-minanch);var o119h=Math.random()*(maxh-minh);
var o120x=Math.random()*(maxx-minx);var o120y=Math.random()*(maxy-miny);
var o120anch=Math.random()*(maxanch-minanch);var o120h=Math.random()*(maxh-minh);
var o121x=Math.random()*(maxx-minx);var o121y=Math.random()*(maxy-miny);
var o121anch=Math.random()*(maxanch-minanch);var o121h=Math.random()*(maxh-minh);
var o122x=Math.random()*(maxx-minx);var o122y=Math.random()*(maxy-miny);
var o122anch=Math.random()*(maxanch-minanch);var o122h=Math.random()*(maxh-minh);
var o123x=Math.random()*(maxx-minx);var o123y=Math.random()*(maxy-miny);
var o123anch=Math.random()*(maxanch-minanch);var o123h=Math.random()*(maxh-minh);
var o124x=Math.random()*(maxx-minx);var o124y=Math.random()*(maxy-miny);
var o124anch=Math.random()*(maxanch-minanch);var o124h=Math.random()*(maxh-minh);
var o125x=Math.random()*(maxx-minx);var o125y=Math.random()*(maxy-miny);
var o125anch=Math.random()*(maxanch-minanch);var o125h=Math.random()*(maxh-minh);
var o126x=Math.random()*(maxx-minx);var o126y=Math.random()*(maxy-miny);
var o126anch=Math.random()*(maxanch-minanch);var o126h=Math.random()*(maxh-minh);
var o127x=Math.random()*(maxx-minx);var o127y=Math.random()*(maxy-miny);
var o127anch=Math.random()*(maxanch-minanch);var o127h=Math.random()*(maxh-minh);
var o128x=Math.random()*(maxx-minx);var o128y=Math.random()*(maxy-miny);
var o128anch=Math.random()*(maxanch-minanch);var o128h=Math.random()*(maxh-minh);
var o129x=Math.random()*(maxx-minx);var o129y=Math.random()*(maxy-miny);
var o129anch=Math.random()*(maxanch-minanch);var o129h=Math.random()*(maxh-minh);
var o130x=Math.random()*(maxx-minx);var o130y=Math.random()*(maxy-miny);
var o130anch=Math.random()*(maxanch-minanch);var o130h=Math.random()*(maxh-minh);
var o131x=Math.random()*(maxx-minx);var o131y=Math.random()*(maxy-miny);
var o131anch=Math.random()*(maxanch-minanch);var o131h=Math.random()*(maxh-minh);
var o132x=Math.random()*(maxx-minx);var o132y=Math.random()*(maxy-miny);
var o132anch=Math.random()*(maxanch-minanch);var o132h=Math.random()*(maxh-minh);
var o133x=Math.random()*(maxx-minx);var o133y=Math.random()*(maxy-miny);
var o133anch=Math.random()*(maxanch-minanch);var o133h=Math.random()*(maxh-minh);
var o134x=Math.random()*(maxx-minx);var o134y=Math.random()*(maxy-miny);
var o134anch=Math.random()*(maxanch-minanch);var o134h=Math.random()*(maxh-minh);
var o135x=Math.random()*(maxx-minx);var o135y=Math.random()*(maxy-miny);
var o135anch=Math.random()*(maxanch-minanch);var o135h=Math.random()*(maxh-minh);
var o136x=Math.random()*(maxx-minx);var o136y=Math.random()*(maxy-miny);
var o136anch=Math.random()*(maxanch-minanch);var o136h=Math.random()*(maxh-minh);
var o137x=Math.random()*(maxx-minx);var o137y=Math.random()*(maxy-miny);
var o137anch=Math.random()*(maxanch-minanch);var o137h=Math.random()*(maxh-minh);
var o138x=Math.random()*(maxx-minx);var o138y=Math.random()*(maxy-miny);
var o138anch=Math.random()*(maxanch-minanch);var o138h=Math.random()*(maxh-minh);
var o139x=Math.random()*(maxx-minx);var o139y=Math.random()*(maxy-miny);
var o139anch=Math.random()*(maxanch-minanch);var o139h=Math.random()*(maxh-minh);
var o140x=Math.random()*(maxx-minx);var o140y=Math.random()*(maxy-miny);
var o140anch=Math.random()*(maxanch-minanch);var o140h=Math.random()*(maxh-minh);
var o141x=Math.random()*(maxx-minx);var o141y=Math.random()*(maxy-miny);
var o141anch=Math.random()*(maxanch-minanch);var o141h=Math.random()*(maxh-minh);
var o142x=Math.random()*(maxx-minx);var o142y=Math.random()*(maxy-miny);
var o142anch=Math.random()*(maxanch-minanch);var o142h=Math.random()*(maxh-minh);
var o143x=Math.random()*(maxx-minx);var o143y=Math.random()*(maxy-miny);
var o143anch=Math.random()*(maxanch-minanch);var o143h=Math.random()*(maxh-minh);
var o144x=Math.random()*(maxx-minx);var o144y=Math.random()*(maxy-miny);
var o144anch=Math.random()*(maxanch-minanch);var o144h=Math.random()*(maxh-minh);
var o145x=Math.random()*(maxx-minx);var o145y=Math.random()*(maxy-miny);
var o145anch=Math.random()*(maxanch-minanch);var o145h=Math.random()*(maxh-minh);
var o146x=Math.random()*(maxx-minx);var o146y=Math.random()*(maxy-miny);
var o146anch=Math.random()*(maxanch-minanch);var o146h=Math.random()*(maxh-minh);
var o147x=Math.random()*(maxx-minx);var o147y=Math.random()*(maxy-miny);
var o147anch=Math.random()*(maxanch-minanch);var o147h=Math.random()*(maxh-minh);
var o148x=Math.random()*(maxx-minx);var o148y=Math.random()*(maxy-miny);
var o148anch=Math.random()*(maxanch-minanch);var o148h=Math.random()*(maxh-minh);
var o149x=Math.random()*(maxx-minx);var o149y=Math.random()*(maxy-miny);
var o149anch=Math.random()*(maxanch-minanch);var o149h=Math.random()*(maxh-minh);
var o150x=Math.random()*(maxx-minx);var o150y=Math.random()*(maxy-miny);
var o150anch=Math.random()*(maxanch-minanch);var o150h=Math.random()*(maxh-minh);
var o151x=Math.random()*(maxx-minx);var o151y=Math.random()*(maxy-miny);
var o151anch=Math.random()*(maxanch-minanch);var o151h=Math.random()*(maxh-minh);
var o152x=Math.random()*(maxx-minx);var o152y=Math.random()*(maxy-miny);
var o152anch=Math.random()*(maxanch-minanch);var o152h=Math.random()*(maxh-minh);
var o153x=Math.random()*(maxx-minx);var o153y=Math.random()*(maxy-miny);
var o153anch=Math.random()*(maxanch-minanch);var o153h=Math.random()*(maxh-minh);
var o154x=Math.random()*(maxx-minx);var o154y=Math.random()*(maxy-miny);
var o154anch=Math.random()*(maxanch-minanch);var o154h=Math.random()*(maxh-minh);
var o155x=Math.random()*(maxx-minx);var o155y=Math.random()*(maxy-miny);
var o155anch=Math.random()*(maxanch-minanch);var o155h=Math.random()*(maxh-minh);
var o156x=Math.random()*(maxx-minx);var o156y=Math.random()*(maxy-miny);
var o156anch=Math.random()*(maxanch-minanch);var o156h=Math.random()*(maxh-minh);
var o157x=Math.random()*(maxx-minx);var o157y=Math.random()*(maxy-miny);
var o157anch=Math.random()*(maxanch-minanch);var o157h=Math.random()*(maxh-minh);
var o158x=Math.random()*(maxx-minx);var o158y=Math.random()*(maxy-miny);
var o158anch=Math.random()*(maxanch-minanch);var o158h=Math.random()*(maxh-minh);
var o159x=Math.random()*(maxx-minx);var o159y=Math.random()*(maxy-miny);
var o159anch=Math.random()*(maxanch-minanch);var o159h=Math.random()*(maxh-minh);
var o160x=Math.random()*(maxx-minx);var o160y=Math.random()*(maxy-miny);
var o160anch=Math.random()*(maxanch-minanch);var o160h=Math.random()*(maxh-minh);
var o161x=Math.random()*(maxx-minx);var o161y=Math.random()*(maxy-miny);
var o161anch=Math.random()*(maxanch-minanch);var o161h=Math.random()*(maxh-minh);
var o162x=Math.random()*(maxx-minx);var o162y=Math.random()*(maxy-miny);
var o162anch=Math.random()*(maxanch-minanch);var o162h=Math.random()*(maxh-minh);
var o163x=Math.random()*(maxx-minx);var o163y=Math.random()*(maxy-miny);
var o163anch=Math.random()*(maxanch-minanch);var o163h=Math.random()*(maxh-minh);
var o164x=Math.random()*(maxx-minx);var o164y=Math.random()*(maxy-miny);
var o164anch=Math.random()*(maxanch-minanch);var o164h=Math.random()*(maxh-minh);
var o165x=Math.random()*(maxx-minx);var o165y=Math.random()*(maxy-miny);
var o165anch=Math.random()*(maxanch-minanch);var o165h=Math.random()*(maxh-minh);
var o166x=Math.random()*(maxx-minx);var o166y=Math.random()*(maxy-miny);
var o166anch=Math.random()*(maxanch-minanch);var o166h=Math.random()*(maxh-minh);
var o167x=Math.random()*(maxx-minx);var o167y=Math.random()*(maxy-miny);
var o167anch=Math.random()*(maxanch-minanch);var o167h=Math.random()*(maxh-minh);
var o168x=Math.random()*(maxx-minx);var o168y=Math.random()*(maxy-miny);
var o168anch=Math.random()*(maxanch-minanch);var o168h=Math.random()*(maxh-minh);
var o169x=Math.random()*(maxx-minx);var o169y=Math.random()*(maxy-miny);
var o169anch=Math.random()*(maxanch-minanch);var o169h=Math.random()*(maxh-minh);
var o170x=Math.random()*(maxx-minx);var o170y=Math.random()*(maxy-miny);
var o170anch=Math.random()*(maxanch-minanch);var o170h=Math.random()*(maxh-minh);
var o171x=Math.random()*(maxx-minx);var o171y=Math.random()*(maxy-miny);
var o171anch=Math.random()*(maxanch-minanch);var o171h=Math.random()*(maxh-minh);
var o172x=Math.random()*(maxx-minx);var o172y=Math.random()*(maxy-miny);
var o172anch=Math.random()*(maxanch-minanch);var o172h=Math.random()*(maxh-minh);
var o173x=Math.random()*(maxx-minx);var o173y=Math.random()*(maxy-miny);
var o173anch=Math.random()*(maxanch-minanch);var o173h=Math.random()*(maxh-minh);
var o174x=Math.random()*(maxx-minx);var o174y=Math.random()*(maxy-miny);
var o174anch=Math.random()*(maxanch-minanch);var o174h=Math.random()*(maxh-minh);
var o175x=Math.random()*(maxx-minx);var o175y=Math.random()*(maxy-miny);
var o175anch=Math.random()*(maxanch-minanch);var o175h=Math.random()*(maxh-minh);
var o176x=Math.random()*(maxx-minx);var o176y=Math.random()*(maxy-miny);
var o176anch=Math.random()*(maxanch-minanch);var o176h=Math.random()*(maxh-minh);
var o177x=Math.random()*(maxx-minx);var o177y=Math.random()*(maxy-miny);
var o177anch=Math.random()*(maxanch-minanch);var o177h=Math.random()*(maxh-minh);
var o178x=Math.random()*(maxx-minx);var o178y=Math.random()*(maxy-miny);
var o178anch=Math.random()*(maxanch-minanch);var o178h=Math.random()*(maxh-minh);
var o179x=Math.random()*(maxx-minx);var o179y=Math.random()*(maxy-miny);
var o179anch=Math.random()*(maxanch-minanch);var o179h=Math.random()*(maxh-minh);
var o180x=Math.random()*(maxx-minx);var o180y=Math.random()*(maxy-miny);
var o180anch=Math.random()*(maxanch-minanch);var o180h=Math.random()*(maxh-minh);
var o181x=Math.random()*(maxx-minx);var o181y=Math.random()*(maxy-miny);
var o181anch=Math.random()*(maxanch-minanch);var o181h=Math.random()*(maxh-minh);
var o182x=Math.random()*(maxx-minx);var o182y=Math.random()*(maxy-miny);
var o182anch=Math.random()*(maxanch-minanch);var o182h=Math.random()*(maxh-minh);
var o183x=Math.random()*(maxx-minx);var o183y=Math.random()*(maxy-miny);
var o183anch=Math.random()*(maxanch-minanch);var o183h=Math.random()*(maxh-minh);
var o184x=Math.random()*(maxx-minx);var o184y=Math.random()*(maxy-miny);
var o184anch=Math.random()*(maxanch-minanch);var o184h=Math.random()*(maxh-minh);
var o185x=Math.random()*(maxx-minx);var o185y=Math.random()*(maxy-miny);
var o185anch=Math.random()*(maxanch-minanch);var o185h=Math.random()*(maxh-minh);
var o186x=Math.random()*(maxx-minx);var o186y=Math.random()*(maxy-miny);
var o186anch=Math.random()*(maxanch-minanch);var o186h=Math.random()*(maxh-minh);
var o187x=Math.random()*(maxx-minx);var o187y=Math.random()*(maxy-miny);
var o187anch=Math.random()*(maxanch-minanch);var o187h=Math.random()*(maxh-minh);
var o188x=Math.random()*(maxx-minx);var o188y=Math.random()*(maxy-miny);
var o188anch=Math.random()*(maxanch-minanch);var o188h=Math.random()*(maxh-minh);
var o189x=Math.random()*(maxx-minx);var o189y=Math.random()*(maxy-miny);
var o189anch=Math.random()*(maxanch-minanch);var o189h=Math.random()*(maxh-minh);
var o190x=Math.random()*(maxx-minx);var o190y=Math.random()*(maxy-miny);
var o190anch=Math.random()*(maxanch-minanch);var o190h=Math.random()*(maxh-minh);
var o191x=Math.random()*(maxx-minx);var o191y=Math.random()*(maxy-miny);
var o191anch=Math.random()*(maxanch-minanch);var o191h=Math.random()*(maxh-minh);
var o192x=Math.random()*(maxx-minx);var o192y=Math.random()*(maxy-miny);
var o192anch=Math.random()*(maxanch-minanch);var o192h=Math.random()*(maxh-minh);
var o193x=Math.random()*(maxx-minx);var o193y=Math.random()*(maxy-miny);
var o193anch=Math.random()*(maxanch-minanch);var o193h=Math.random()*(maxh-minh);
var o194x=Math.random()*(maxx-minx);var o194y=Math.random()*(maxy-miny);
var o194anch=Math.random()*(maxanch-minanch);var o194h=Math.random()*(maxh-minh);
var o195x=Math.random()*(maxx-minx);var o195y=Math.random()*(maxy-miny);
var o195anch=Math.random()*(maxanch-minanch);var o195h=Math.random()*(maxh-minh);
var o196x=Math.random()*(maxx-minx);var o196y=Math.random()*(maxy-miny);
var o196anch=Math.random()*(maxanch-minanch);var o196h=Math.random()*(maxh-minh);
var o197x=Math.random()*(maxx-minx);var o197y=Math.random()*(maxy-miny);
var o197anch=Math.random()*(maxanch-minanch);var o197h=Math.random()*(maxh-minh);
var o198x=Math.random()*(maxx-minx);var o198y=Math.random()*(maxy-miny);
var o198anch=Math.random()*(maxanch-minanch);var o198h=Math.random()*(maxh-minh);
var o199x=Math.random()*(maxx-minx);var o199y=Math.random()*(maxy-miny);
var o199anch=Math.random()*(maxanch-minanch);var o199h=Math.random()*(maxh-minh);
var o200x=Math.random()*(maxx-minx);var o200y=Math.random()*(maxy-miny);
var o200anch=Math.random()*(maxanch-minanch);var o200h=Math.random()*(maxh-minh);
var o201x=Math.random()*(maxx-minx);var o201y=Math.random()*(maxy-miny);
var o201anch=Math.random()*(maxanch-minanch);var o201h=Math.random()*(maxh-minh);
var o202x=Math.random()*(maxx-minx);var o202y=Math.random()*(maxy-miny);
var o202anch=Math.random()*(maxanch-minanch);var o202h=Math.random()*(maxh-minh);
var o203x=Math.random()*(maxx-minx);var o203y=Math.random()*(maxy-miny);
var o203anch=Math.random()*(maxanch-minanch);var o203h=Math.random()*(maxh-minh);
var o204x=Math.random()*(maxx-minx);var o204y=Math.random()*(maxy-miny);
var o204anch=Math.random()*(maxanch-minanch);var o204h=Math.random()*(maxh-minh);
var o205x=Math.random()*(maxx-minx);var o205y=Math.random()*(maxy-miny);
var o205anch=Math.random()*(maxanch-minanch);var o205h=Math.random()*(maxh-minh);
var o206x=Math.random()*(maxx-minx);var o206y=Math.random()*(maxy-miny);
var o206anch=Math.random()*(maxanch-minanch);var o206h=Math.random()*(maxh-minh);
var o207x=Math.random()*(maxx-minx);var o207y=Math.random()*(maxy-miny);
var o207anch=Math.random()*(maxanch-minanch);var o207h=Math.random()*(maxh-minh);
var o208x=Math.random()*(maxx-minx);var o208y=Math.random()*(maxy-miny);
var o208anch=Math.random()*(maxanch-minanch);var o208h=Math.random()*(maxh-minh);
var o209x=Math.random()*(maxx-minx);var o209y=Math.random()*(maxy-miny);
var o209anch=Math.random()*(maxanch-minanch);var o209h=Math.random()*(maxh-minh);
var o210x=Math.random()*(maxx-minx);var o210y=Math.random()*(maxy-miny);
var o210anch=Math.random()*(maxanch-minanch);var o210h=Math.random()*(maxh-minh);
var o211x=Math.random()*(maxx-minx);var o211y=Math.random()*(maxy-miny);
var o211anch=Math.random()*(maxanch-minanch);var o211h=Math.random()*(maxh-minh);
var o212x=Math.random()*(maxx-minx);var o212y=Math.random()*(maxy-miny);
var o212anch=Math.random()*(maxanch-minanch);var o212h=Math.random()*(maxh-minh);
var o213x=Math.random()*(maxx-minx);var o213y=Math.random()*(maxy-miny);
var o213anch=Math.random()*(maxanch-minanch);var o213h=Math.random()*(maxh-minh);
var o214x=Math.random()*(maxx-minx);var o214y=Math.random()*(maxy-miny);
var o214anch=Math.random()*(maxanch-minanch);var o214h=Math.random()*(maxh-minh);
var o215x=Math.random()*(maxx-minx);var o215y=Math.random()*(maxy-miny);
var o215anch=Math.random()*(maxanch-minanch);var o215h=Math.random()*(maxh-minh);
var o216x=Math.random()*(maxx-minx);var o216y=Math.random()*(maxy-miny);
var o216anch=Math.random()*(maxanch-minanch);var o216h=Math.random()*(maxh-minh);
var o217x=Math.random()*(maxx-minx);var o217y=Math.random()*(maxy-miny);
var o217anch=Math.random()*(maxanch-minanch);var o217h=Math.random()*(maxh-minh);
var o218x=Math.random()*(maxx-minx);var o218y=Math.random()*(maxy-miny);
var o218anch=Math.random()*(maxanch-minanch);var o218h=Math.random()*(maxh-minh);
var o219x=Math.random()*(maxx-minx);var o219y=Math.random()*(maxy-miny);
var o219anch=Math.random()*(maxanch-minanch);var o219h=Math.random()*(maxh-minh);
var o220x=Math.random()*(maxx-minx);var o220y=Math.random()*(maxy-miny);
var o220anch=Math.random()*(maxanch-minanch);var o220h=Math.random()*(maxh-minh);
var o221x=Math.random()*(maxx-minx);var o221y=Math.random()*(maxy-miny);
var o221anch=Math.random()*(maxanch-minanch);var o221h=Math.random()*(maxh-minh);
var o222x=Math.random()*(maxx-minx);var o222y=Math.random()*(maxy-miny);
var o222anch=Math.random()*(maxanch-minanch);var o222h=Math.random()*(maxh-minh);
var o223x=Math.random()*(maxx-minx);var o223y=Math.random()*(maxy-miny);
var o223anch=Math.random()*(maxanch-minanch);var o223h=Math.random()*(maxh-minh);
var o224x=Math.random()*(maxx-minx);var o224y=Math.random()*(maxy-miny);
var o224anch=Math.random()*(maxanch-minanch);var o224h=Math.random()*(maxh-minh);
var o225x=Math.random()*(maxx-minx);var o225y=Math.random()*(maxy-miny);
var o225anch=Math.random()*(maxanch-minanch);var o225h=Math.random()*(maxh-minh);
var o226x=Math.random()*(maxx-minx);var o226y=Math.random()*(maxy-miny);
var o226anch=Math.random()*(maxanch-minanch);var o226h=Math.random()*(maxh-minh);
var o227x=Math.random()*(maxx-minx);var o227y=Math.random()*(maxy-miny);
var o227anch=Math.random()*(maxanch-minanch);var o227h=Math.random()*(maxh-minh);
var o228x=Math.random()*(maxx-minx);var o228y=Math.random()*(maxy-miny);
var o228anch=Math.random()*(maxanch-minanch);var o228h=Math.random()*(maxh-minh);
var o229x=Math.random()*(maxx-minx);var o229y=Math.random()*(maxy-miny);
var o229anch=Math.random()*(maxanch-minanch);var o229h=Math.random()*(maxh-minh);
var o230x=Math.random()*(maxx-minx);var o230y=Math.random()*(maxy-miny);
var o230anch=Math.random()*(maxanch-minanch);var o230h=Math.random()*(maxh-minh);
var o231x=Math.random()*(maxx-minx);var o231y=Math.random()*(maxy-miny);
var o231anch=Math.random()*(maxanch-minanch);var o231h=Math.random()*(maxh-minh);
var o232x=Math.random()*(maxx-minx);var o232y=Math.random()*(maxy-miny);
var o232anch=Math.random()*(maxanch-minanch);var o232h=Math.random()*(maxh-minh);
var o233x=Math.random()*(maxx-minx);var o233y=Math.random()*(maxy-miny);
var o233anch=Math.random()*(maxanch-minanch);var o233h=Math.random()*(maxh-minh);
var o234x=Math.random()*(maxx-minx);var o234y=Math.random()*(maxy-miny);
var o234anch=Math.random()*(maxanch-minanch);var o234h=Math.random()*(maxh-minh);
var o235x=Math.random()*(maxx-minx);var o235y=Math.random()*(maxy-miny);
var o235anch=Math.random()*(maxanch-minanch);var o235h=Math.random()*(maxh-minh);
var o236x=Math.random()*(maxx-minx);var o236y=Math.random()*(maxy-miny);
var o236anch=Math.random()*(maxanch-minanch);var o236h=Math.random()*(maxh-minh);
var o237x=Math.random()*(maxx-minx);var o237y=Math.random()*(maxy-miny);
var o237anch=Math.random()*(maxanch-minanch);var o237h=Math.random()*(maxh-minh);
var o238x=Math.random()*(maxx-minx);var o238y=Math.random()*(maxy-miny);
var o238anch=Math.random()*(maxanch-minanch);var o238h=Math.random()*(maxh-minh);
var o239x=Math.random()*(maxx-minx);var o239y=Math.random()*(maxy-miny);
var o239anch=Math.random()*(maxanch-minanch);var o239h=Math.random()*(maxh-minh);
var o240x=Math.random()*(maxx-minx);var o240y=Math.random()*(maxy-miny);
var o240anch=Math.random()*(maxanch-minanch);var o240h=Math.random()*(maxh-minh);
var o241x=Math.random()*(maxx-minx);var o241y=Math.random()*(maxy-miny);
var o241anch=Math.random()*(maxanch-minanch);var o241h=Math.random()*(maxh-minh);
var o242x=Math.random()*(maxx-minx);var o242y=Math.random()*(maxy-miny);
var o242anch=Math.random()*(maxanch-minanch);var o242h=Math.random()*(maxh-minh);
var o243x=Math.random()*(maxx-minx);var o243y=Math.random()*(maxy-miny);
var o243anch=Math.random()*(maxanch-minanch);var o243h=Math.random()*(maxh-minh);
var o244x=Math.random()*(maxx-minx);var o244y=Math.random()*(maxy-miny);
var o244anch=Math.random()*(maxanch-minanch);var o244h=Math.random()*(maxh-minh);
var o245x=Math.random()*(maxx-minx);var o245y=Math.random()*(maxy-miny);
var o245anch=Math.random()*(maxanch-minanch);var o245h=Math.random()*(maxh-minh);
var o246x=Math.random()*(maxx-minx);var o246y=Math.random()*(maxy-miny);
var o246anch=Math.random()*(maxanch-minanch);var o246h=Math.random()*(maxh-minh);
var o247x=Math.random()*(maxx-minx);var o247y=Math.random()*(maxy-miny);
var o247anch=Math.random()*(maxanch-minanch);var o247h=Math.random()*(maxh-minh);
var o248x=Math.random()*(maxx-minx);var o248y=Math.random()*(maxy-miny);
var o248anch=Math.random()*(maxanch-minanch);var o248h=Math.random()*(maxh-minh);
var o249x=Math.random()*(maxx-minx);var o249y=Math.random()*(maxy-miny);
var o249anch=Math.random()*(maxanch-minanch);var o249h=Math.random()*(maxh-minh);
var o250x=Math.random()*(maxx-minx);var o250y=Math.random()*(maxy-miny);
var o250anch=Math.random()*(maxanch-minanch);var o250h=Math.random()*(maxh-minh);
var o251x=Math.random()*(maxx-minx);var o251y=Math.random()*(maxy-miny);
var o251anch=Math.random()*(maxanch-minanch);var o251h=Math.random()*(maxh-minh);
var o252x=Math.random()*(maxx-minx);var o252y=Math.random()*(maxy-miny);
var o252anch=Math.random()*(maxanch-minanch);var o252h=Math.random()*(maxh-minh);
var o253x=Math.random()*(maxx-minx);var o253y=Math.random()*(maxy-miny);
var o253anch=Math.random()*(maxanch-minanch);var o253h=Math.random()*(maxh-minh);
var o254x=Math.random()*(maxx-minx);var o254y=Math.random()*(maxy-miny);
var o254anch=Math.random()*(maxanch-minanch);var o254h=Math.random()*(maxh-minh);
var o255x=Math.random()*(maxx-minx);var o255y=Math.random()*(maxy-miny);
var o255anch=Math.random()*(maxanch-minanch);var o255h=Math.random()*(maxh-minh);
var o256x=Math.random()*(maxx-minx);var o256y=Math.random()*(maxy-miny);
var o256anch=Math.random()*(maxanch-minanch);var o256h=Math.random()*(maxh-minh);
var o257x=Math.random()*(maxx-minx);var o257y=Math.random()*(maxy-miny);
var o257anch=Math.random()*(maxanch-minanch);var o257h=Math.random()*(maxh-minh);
var o258x=Math.random()*(maxx-minx);var o258y=Math.random()*(maxy-miny);
var o258anch=Math.random()*(maxanch-minanch);var o258h=Math.random()*(maxh-minh);
var o259x=Math.random()*(maxx-minx);var o259y=Math.random()*(maxy-miny);
var o259anch=Math.random()*(maxanch-minanch);var o259h=Math.random()*(maxh-minh);
var o260x=Math.random()*(maxx-minx);var o260y=Math.random()*(maxy-miny);
var o260anch=Math.random()*(maxanch-minanch);var o260h=Math.random()*(maxh-minh);
var o261x=Math.random()*(maxx-minx);var o261y=Math.random()*(maxy-miny);
var o261anch=Math.random()*(maxanch-minanch);var o261h=Math.random()*(maxh-minh);
var o262x=Math.random()*(maxx-minx);var o262y=Math.random()*(maxy-miny);
var o262anch=Math.random()*(maxanch-minanch);var o262h=Math.random()*(maxh-minh);
var o263x=Math.random()*(maxx-minx);var o263y=Math.random()*(maxy-miny);
var o263anch=Math.random()*(maxanch-minanch);var o263h=Math.random()*(maxh-minh);
var o264x=Math.random()*(maxx-minx);var o264y=Math.random()*(maxy-miny);
var o264anch=Math.random()*(maxanch-minanch);var o264h=Math.random()*(maxh-minh);
var o265x=Math.random()*(maxx-minx);var o265y=Math.random()*(maxy-miny);
var o265anch=Math.random()*(maxanch-minanch);var o265h=Math.random()*(maxh-minh);
var o266x=Math.random()*(maxx-minx);var o266y=Math.random()*(maxy-miny);
var o266anch=Math.random()*(maxanch-minanch);var o266h=Math.random()*(maxh-minh);
var o267x=Math.random()*(maxx-minx);var o267y=Math.random()*(maxy-miny);
var o267anch=Math.random()*(maxanch-minanch);var o267h=Math.random()*(maxh-minh);
var o268x=Math.random()*(maxx-minx);var o268y=Math.random()*(maxy-miny);
var o268anch=Math.random()*(maxanch-minanch);var o268h=Math.random()*(maxh-minh);
var o269x=Math.random()*(maxx-minx);var o269y=Math.random()*(maxy-miny);
var o269anch=Math.random()*(maxanch-minanch);var o269h=Math.random()*(maxh-minh);
var o270x=Math.random()*(maxx-minx);var o270y=Math.random()*(maxy-miny);
var o270anch=Math.random()*(maxanch-minanch);var o270h=Math.random()*(maxh-minh);
var o271x=Math.random()*(maxx-minx);var o271y=Math.random()*(maxy-miny);
var o271anch=Math.random()*(maxanch-minanch);var o271h=Math.random()*(maxh-minh);
var o272x=Math.random()*(maxx-minx);var o272y=Math.random()*(maxy-miny);
var o272anch=Math.random()*(maxanch-minanch);var o272h=Math.random()*(maxh-minh);
var o273x=Math.random()*(maxx-minx);var o273y=Math.random()*(maxy-miny);
var o273anch=Math.random()*(maxanch-minanch);var o273h=Math.random()*(maxh-minh);
var o274x=Math.random()*(maxx-minx);var o274y=Math.random()*(maxy-miny);
var o274anch=Math.random()*(maxanch-minanch);var o274h=Math.random()*(maxh-minh);
var o275x=Math.random()*(maxx-minx);var o275y=Math.random()*(maxy-miny);
var o275anch=Math.random()*(maxanch-minanch);var o275h=Math.random()*(maxh-minh);
var o276x=Math.random()*(maxx-minx);var o276y=Math.random()*(maxy-miny);
var o276anch=Math.random()*(maxanch-minanch);var o276h=Math.random()*(maxh-minh);
var o277x=Math.random()*(maxx-minx);var o277y=Math.random()*(maxy-miny);
var o277anch=Math.random()*(maxanch-minanch);var o277h=Math.random()*(maxh-minh);
var o278x=Math.random()*(maxx-minx);var o278y=Math.random()*(maxy-miny);
var o278anch=Math.random()*(maxanch-minanch);var o278h=Math.random()*(maxh-minh);
var o279x=Math.random()*(maxx-minx);var o279y=Math.random()*(maxy-miny);
var o279anch=Math.random()*(maxanch-minanch);var o279h=Math.random()*(maxh-minh);
var o280x=Math.random()*(maxx-minx);var o280y=Math.random()*(maxy-miny);
var o280anch=Math.random()*(maxanch-minanch);var o280h=Math.random()*(maxh-minh);
var o281x=Math.random()*(maxx-minx);var o281y=Math.random()*(maxy-miny);
var o281anch=Math.random()*(maxanch-minanch);var o281h=Math.random()*(maxh-minh);
var o282x=Math.random()*(maxx-minx);var o282y=Math.random()*(maxy-miny);
var o282anch=Math.random()*(maxanch-minanch);var o282h=Math.random()*(maxh-minh);
var o283x=Math.random()*(maxx-minx);var o283y=Math.random()*(maxy-miny);
var o283anch=Math.random()*(maxanch-minanch);var o283h=Math.random()*(maxh-minh);
var o284x=Math.random()*(maxx-minx);var o284y=Math.random()*(maxy-miny);
var o284anch=Math.random()*(maxanch-minanch);var o284h=Math.random()*(maxh-minh);
var o285x=Math.random()*(maxx-minx);var o285y=Math.random()*(maxy-miny);
var o285anch=Math.random()*(maxanch-minanch);var o285h=Math.random()*(maxh-minh);
var o286x=Math.random()*(maxx-minx);var o286y=Math.random()*(maxy-miny);
var o286anch=Math.random()*(maxanch-minanch);var o286h=Math.random()*(maxh-minh);
var o287x=Math.random()*(maxx-minx);var o287y=Math.random()*(maxy-miny);
var o287anch=Math.random()*(maxanch-minanch);var o287h=Math.random()*(maxh-minh);
var o288x=Math.random()*(maxx-minx);var o288y=Math.random()*(maxy-miny);
var o288anch=Math.random()*(maxanch-minanch);var o288h=Math.random()*(maxh-minh);
var o289x=Math.random()*(maxx-minx);var o289y=Math.random()*(maxy-miny);
var o289anch=Math.random()*(maxanch-minanch);var o289h=Math.random()*(maxh-minh);
var o290x=Math.random()*(maxx-minx);var o290y=Math.random()*(maxy-miny);
var o290anch=Math.random()*(maxanch-minanch);var o290h=Math.random()*(maxh-minh);
var o291x=Math.random()*(maxx-minx);var o291y=Math.random()*(maxy-miny);
var o291anch=Math.random()*(maxanch-minanch);var o291h=Math.random()*(maxh-minh);
var o292x=Math.random()*(maxx-minx);var o292y=Math.random()*(maxy-miny);
var o292anch=Math.random()*(maxanch-minanch);var o292h=Math.random()*(maxh-minh);
var o293x=Math.random()*(maxx-minx);var o293y=Math.random()*(maxy-miny);
var o293anch=Math.random()*(maxanch-minanch);var o293h=Math.random()*(maxh-minh);
var o294x=Math.random()*(maxx-minx);var o294y=Math.random()*(maxy-miny);
var o294anch=Math.random()*(maxanch-minanch);var o294h=Math.random()*(maxh-minh);
var o295x=Math.random()*(maxx-minx);var o295y=Math.random()*(maxy-miny);
var o295anch=Math.random()*(maxanch-minanch);var o295h=Math.random()*(maxh-minh);
var o296x=Math.random()*(maxx-minx);var o296y=Math.random()*(maxy-miny);
var o296anch=Math.random()*(maxanch-minanch);var o296h=Math.random()*(maxh-minh);
var o297x=Math.random()*(maxx-minx);var o297y=Math.random()*(maxy-miny);
var o297anch=Math.random()*(maxanch-minanch);var o297h=Math.random()*(maxh-minh);
var o298x=Math.random()*(maxx-minx);var o298y=Math.random()*(maxy-miny);
var o298anch=Math.random()*(maxanch-minanch);var o298h=Math.random()*(maxh-minh);
var o299x=Math.random()*(maxx-minx);var o299y=Math.random()*(maxy-miny);
var o299anch=Math.random()*(maxanch-minanch);var o299h=Math.random()*(maxh-minh);
var o300x=Math.random()*(maxx-minx);var o300y=Math.random()*(maxy-miny);
var o300anch=Math.random()*(maxanch-minanch);var o300h=Math.random()*(maxh-minh);

function accion(datos) {
    draw();
    while (true){
	if (datos.keyDown == tecla.w){
	    ypro = ypro - 3;
	    draw();}
    }
}

function draw() {//dibujar en el canvaz.
    lienzo.fillStyle="rgb(0, 0, 0)";
    lienzo.fillRect(0,0,900,500);
    lienzo.fillStyle="rgb(250, 250, 0)";
    lienzo.fillRect(xpro,ypro,30,30);
    lienzo.fillStyle="rgb(0,250,0)";
    lienzo.fillRect(p1x,p1y,p1anch,p1h);
    lienzo.fillRect(p2x,p2y,p2anch,p2h);
    lienzo.fillRect(p3x,p3y,p3anch,p3h);
    lienzo.fillRect(p4x,p4y,p4anch,p4h);
    lienzo.fillRect(p5x,p5y,p5anch,p5h);
    lienzo.fillRect(p6x,p6y,p6anch,p6h);
    lienzo.fillRect(p7x,p7y,p7anch,p7h);
    lienzo.fillRect(p8x,p8y,p8anch,p8h);
    lienzo.fillRect(p9x,p9y,p9anch,p9h);
    lienzo.fillRect(p10x,p10y,p10anch,p10h);
    lienzo.fillRect(p11x,p11y,p11anch,p11h);
    lienzo.fillRect(p12x,p12y,p12anch,p12h);
    lienzo.fillRect(p13x,p13y,p13anch,p13h);
    lienzo.fillRect(p14x,p14y,p14anch,p14h);
    lienzo.fillRect(p15x,p15y,p15anch,p15h);
    lienzo.fillRect(p16x,p16y,p16anch,p16h);
    lienzo.fillRect(p17x,p17y,p17anch,p17h);
    lienzo.fillRect(p18x,p18y,p18anch,p18h);
    lienzo.fillRect(p19x,p19y,p19anch,p19h);
    lienzo.fillRect(p20x,p20y,p20anch,p20h);
    lienzo.fillRect(p21x,p21y,p21anch,p21h);
    lienzo.fillRect(p22x,p22y,p22anch,p22h);
    lienzo.fillRect(p23x,p23y,p23anch,p23h);
    lienzo.fillRect(p24x,p24y,p24anch,p24h);
    lienzo.fillRect(p25x,p25y,p25anch,p25h);
    lienzo.fillRect(p26x,p26y,p26anch,p26h);
    lienzo.fillRect(p27x,p27y,p27anch,p27h);
    lienzo.fillRect(p28x,p28y,p28anch,p28h);
    lienzo.fillRect(p29x,p29y,p29anch,p29h);
    lienzo.fillRect(p30x,p30y,p30anch,p30h);
    lienzo.fillRect(p31x,p31y,p31anch,p31h);
    lienzo.fillRect(p32x,p32y,p32anch,p32h);
    lienzo.fillRect(p33x,p33y,p33anch,p33h);
    lienzo.fillRect(p34x,p34y,p34anch,p34h);
    lienzo.fillRect(p35x,p35y,p35anch,p35h);
    lienzo.fillRect(p36x,p36y,p36anch,p36h);
    lienzo.fillRect(p37x,p37y,p37anch,p37h);
    lienzo.fillRect(p38x,p38y,p38anch,p38h);
    lienzo.fillRect(p39x,p39y,p39anch,p39h);
    lienzo.fillRect(p40x,p40y,p40anch,p40h);
    lienzo.fillRect(p41x,p41y,p41anch,p41h);
    lienzo.fillRect(p42x,p42y,p42anch,p42h);
    lienzo.fillRect(p43x,p43y,p43anch,p43h);
    lienzo.fillRect(p44x,p44y,p44anch,p44h);
    lienzo.fillRect(p45x,p45y,p45anch,p45h);
    lienzo.fillRect(p46x,p46y,p46anch,p46h);
    lienzo.fillRect(p47x,p47y,p47anch,p47h);
    lienzo.fillRect(p48x,p48y,p48anch,p48h);
    lienzo.fillRect(p49x,p49y,p49anch,p49h);
    lienzo.fillRect(p50x,p50y,p50anch,p50h);
    lienzo.fillRect(p51x,p51y,p51anch,p51h);
    lienzo.fillRect(p52x,p52y,p52anch,p52h);
    lienzo.fillRect(p53x,p53y,p53anch,p53h);
    lienzo.fillRect(p54x,p54y,p54anch,p54h);
    lienzo.fillRect(p55x,p55y,p55anch,p55h);
    lienzo.fillRect(p56x,p56y,p56anch,p56h);
    lienzo.fillRect(p57x,p57y,p57anch,p57h);
    lienzo.fillRect(p58x,p58y,p58anch,p58h);
    lienzo.fillRect(p59x,p59y,p59anch,p59h);
    lienzo.fillRect(p60x,p60y,p60anch,p60h);
    lienzo.fillRect(p61x,p61y,p61anch,p61h);
    lienzo.fillRect(p62x,p62y,p62anch,p62h);
    lienzo.fillRect(p63x,p63y,p63anch,p63h);
    lienzo.fillRect(p64x,p64y,p64anch,p64h);
    lienzo.fillRect(p65x,p65y,p65anch,p65h);
    lienzo.fillRect(p66x,p66y,p66anch,p66h);
    lienzo.fillRect(p67x,p67y,p67anch,p67h);
    lienzo.fillRect(p68x,p68y,p68anch,p68h);
    lienzo.fillRect(p69x,p69y,p69anch,p69h);
    lienzo.fillRect(p70x,p70y,p70anch,p70h);
    lienzo.fillRect(p71x,p71y,p71anch,p71h);
    lienzo.fillRect(p72x,p72y,p72anch,p72h);
    lienzo.fillRect(p73x,p73y,p73anch,p73h);
    lienzo.fillRect(p74x,p74y,p74anch,p74h);
    lienzo.fillRect(p75x,p75y,p75anch,p75h);
    lienzo.fillRect(p76x,p76y,p76anch,p76h);
    lienzo.fillRect(p77x,p77y,p77anch,p77h);
    lienzo.fillRect(p78x,p78y,p78anch,p78h);
    lienzo.fillRect(p79x,p79y,p79anch,p79h);
    lienzo.fillRect(p80x,p80y,p80anch,p80h);
    lienzo.fillRect(p81x,p81y,p81anch,p81h);
    lienzo.fillRect(p82x,p82y,p82anch,p82h);
    lienzo.fillRect(p83x,p83y,p83anch,p83h);
    lienzo.fillRect(p84x,p84y,p84anch,p84h);
    lienzo.fillRect(p85x,p85y,p85anch,p85h);
    lienzo.fillRect(p86x,p86y,p86anch,p86h);
    lienzo.fillRect(p87x,p87y,p87anch,p87h);
    lienzo.fillRect(p88x,p88y,p88anch,p88h);
    lienzo.fillRect(p89x,p89y,p89anch,p89h);
    lienzo.fillRect(p90x,p90y,p90anch,p90h);
    lienzo.fillRect(p91x,p91y,p91anch,p91h);
    lienzo.fillRect(p92x,p92y,p92anch,p92h);
    lienzo.fillRect(p93x,p93y,p93anch,p93h);
    lienzo.fillRect(p94x,p94y,p94anch,p94h);
    lienzo.fillRect(p95x,p95y,p95anch,p95h);
    lienzo.fillRect(p96x,p96y,p96anch,p96h);
    lienzo.fillRect(p97x,p97y,p97anch,p97h);
    lienzo.fillRect(p98x,p98y,p98anch,p98h);
    lienzo.fillRect(p99x,p99y,p99anch,p99h);
    lienzo.fillRect(p100x,p100y,p100anch,p100h);
    //almas
    lienzo.fillStyle="rgb(250,250,250)";
    lienzo.fillRect(a1x,a1y,a1anch,a1h);
    lienzo.fillRect(a2x,a2y,a2anch,a2h);
    lienzo.fillRect(a3x,a3y,a3anch,a3h);
    lienzo.fillRect(a4x,a4y,a4anch,a4h);
    lienzo.fillRect(a5x,a5y,a5anch,a5h);
    //OBSTACULOS
    lienzo.fillStyle="rgb(250,0,0)";
    lienzo.fillRect(o1x,o1y,o1anch,o1h);
    lienzo.fillRect(o2x,o2y,o2anch,o2h);
    lienzo.fillRect(o3x,o3y,o3anch,o3h);
    lienzo.fillRect(o4x,o4y,o4anch,o4h);
    lienzo.fillRect(o5x,o5y,o5anch,o5h);
    lienzo.fillRect(o6x,o6y,o6anch,o6h);
    lienzo.fillRect(o7x,o7y,o7anch,o7h);
    lienzo.fillRect(o8x,o8y,o8anch,o8h);
    lienzo.fillRect(o9x,o9y,o9anch,o9h);
    lienzo.fillRect(o10x,o10y,o10anch,o10h);
    lienzo.fillRect(o11x,o11y,o11anch,o11h);
    lienzo.fillRect(o12x,o12y,o12anch,o12h);
    lienzo.fillRect(o13x,o13y,o13anch,o13h);
    lienzo.fillRect(o14x,o14y,o14anch,o14h);
    lienzo.fillRect(o15x,o15y,o15anch,o15h);
    lienzo.fillRect(o16x,o16y,o16anch,o16h);
    lienzo.fillRect(o17x,o17y,o17anch,o17h);
    lienzo.fillRect(o18x,o18y,o18anch,o18h);
    lienzo.fillRect(o19x,o19y,o19anch,o19h);
    lienzo.fillRect(o20x,o20y,o20anch,o20h);
    lienzo.fillRect(o21x,o21y,o21anch,o21h);
    lienzo.fillRect(o22x,o22y,o22anch,o22h);
    lienzo.fillRect(o23x,o23y,o23anch,o23h);
    lienzo.fillRect(o24x,o24y,o24anch,o24h);
    lienzo.fillRect(o25x,o25y,o25anch,o25h);
    lienzo.fillRect(o26x,o26y,o26anch,o26h);
    lienzo.fillRect(o27x,o27y,o27anch,o27h);
    lienzo.fillRect(o28x,o28y,o28anch,o28h);
    lienzo.fillRect(o29x,o29y,o29anch,o29h);
    lienzo.fillRect(o30x,o30y,o30anch,o30h);
    lienzo.fillRect(o31x,o31y,o31anch,o31h);
    lienzo.fillRect(o32x,o32y,o32anch,o32h);
    lienzo.fillRect(o33x,o33y,o33anch,o33h);
    lienzo.fillRect(o34x,o34y,o34anch,o34h);
    lienzo.fillRect(o35x,o35y,o35anch,o35h);
    lienzo.fillRect(o36x,o36y,o36anch,o36h);
    lienzo.fillRect(o37x,o37y,o37anch,o37h);
    lienzo.fillRect(o38x,o38y,o38anch,o38h);
    lienzo.fillRect(o39x,o39y,o39anch,o39h);
    lienzo.fillRect(o40x,o40y,o40anch,o40h);
    lienzo.fillRect(o41x,o41y,o41anch,o41h);
    lienzo.fillRect(o42x,o42y,o42anch,o42h);
    lienzo.fillRect(o43x,o43y,o43anch,o43h);
    lienzo.fillRect(o44x,o44y,o44anch,o44h);
    lienzo.fillRect(o45x,o45y,o45anch,o45h);
    lienzo.fillRect(o46x,o46y,o46anch,o46h);
    lienzo.fillRect(o47x,o47y,o47anch,o47h);
    lienzo.fillRect(o48x,o48y,o48anch,o48h);
    lienzo.fillRect(o49x,o49y,o49anch,o49h);
    lienzo.fillRect(o50x,o50y,o50anch,o50h);
    lienzo.fillRect(o51x,o51y,o51anch,o51h);
    lienzo.fillRect(o52x,o52y,o52anch,o52h);
    lienzo.fillRect(o53x,o53y,o53anch,o53h);
    lienzo.fillRect(o54x,o54y,o54anch,o54h);
    lienzo.fillRect(o55x,o55y,o55anch,o55h);
    lienzo.fillRect(o56x,o56y,o56anch,o56h);
    lienzo.fillRect(o57x,o57y,o57anch,o57h);
    lienzo.fillRect(o58x,o58y,o58anch,o58h);
    lienzo.fillRect(o59x,o59y,o59anch,o59h);
    lienzo.fillRect(o60x,o60y,o60anch,o60h);
    lienzo.fillRect(o61x,o61y,o61anch,o61h);
    lienzo.fillRect(o62x,o62y,o62anch,o62h);
    lienzo.fillRect(o63x,o63y,o63anch,o63h);
    lienzo.fillRect(o64x,o64y,o64anch,o64h);
    lienzo.fillRect(o65x,o65y,o65anch,o65h);
    lienzo.fillRect(o66x,o66y,o66anch,o66h);
    lienzo.fillRect(o67x,o67y,o67anch,o67h);
    lienzo.fillRect(o68x,o68y,o68anch,o68h);
    lienzo.fillRect(o69x,o69y,o69anch,o69h);
    lienzo.fillRect(o70x,o70y,o70anch,o70h);
    lienzo.fillRect(o71x,o71y,o71anch,o71h);
    lienzo.fillRect(o72x,o72y,o72anch,o72h);
    lienzo.fillRect(o73x,o73y,o73anch,o73h);
    lienzo.fillRect(o74x,o74y,o74anch,o74h);
    lienzo.fillRect(o75x,o74y,o75anch,o75h);
    lienzo.fillRect(o76x,o76y,o76anch,o76h);
    lienzo.fillRect(o77x,o77y,o77anch,o77h);
    lienzo.fillRect(o78x,o78y,o78anch,o78h);
    lienzo.fillRect(o79x,o79y,o79anch,o79h);
    lienzo.fillRect(o80x,o80y,o80anch,o80h);
    lienzo.fillRect(o81x,o81y,o81anch,o81h);
    lienzo.fillRect(o82x,o82y,o82anch,o82h);
    lienzo.fillRect(o83x,o83y,o83anch,o83h);
    lienzo.fillRect(o84x,o84y,o84anch,o84h);
    lienzo.fillRect(o85x,o85y,o85anch,o85h);
    lienzo.fillRect(o86x,o86y,o86anch,o86h);
    lienzo.fillRect(o87x,o87y,o87anch,o87h);
    lienzo.fillRect(o88x,o88y,o88anch,o88h);
    lienzo.fillRect(o89x,o89y,o89anch,o89h);
    lienzo.fillRect(o90x,o90y,o90anch,o90h);
    lienzo.fillRect(o91x,o91y,o91anch,o91h);
    lienzo.fillRect(o92x,o92y,o92anch,o92h);
    lienzo.fillRect(o93x,o93y,o93anch,o93h);
    lienzo.fillRect(o94x,o94y,o94anch,o94h);
    lienzo.fillRect(o95x,o95y,o95anch,o95h);
    lienzo.fillRect(o96x,o96y,o96anch,o96h);
    lienzo.fillRect(o97x,o97y,o97anch,o97h);
    lienzo.fillRect(o98x,o98y,o98anch,o98h);
    lienzo.fillRect(o99x,o99y,o99anch,o99h);
    lienzo.fillRect(o100x,o100y,o100anch,o100h);
    lienzo.fillRect(o101x,o101y,o101anch,o101h);
    lienzo.fillRect(o102x,o102y,o102anch,o102h);
    lienzo.fillRect(o103x,o103y,o103anch,o103h);
    lienzo.fillRect(o104x,o104y,o104anch,o104h);
    lienzo.fillRect(o105x,o105y,o105anch,o105h);
    lienzo.fillRect(o106x,o106y,o106anch,o106h);
    lienzo.fillRect(o107x,o107y,o107anch,o107h);
    lienzo.fillRect(o108x,o108y,o108anch,o108h);
    lienzo.fillRect(o109x,o109y,o109anch,o109h);
    lienzo.fillRect(o110x,o110y,o110anch,o110h);
    lienzo.fillRect(o111x,o111y,o111anch,o111h);
    lienzo.fillRect(o112x,o112y,o112anch,o112h);
    lienzo.fillRect(o113x,o113y,o113anch,o113h);
    lienzo.fillRect(o114x,o114y,o114anch,o114h);
    lienzo.fillRect(o115x,o115y,o115anch,o115h);
    lienzo.fillRect(o116x,o116y,o116anch,o116h);
    lienzo.fillRect(o117x,o117y,o117anch,o117h);
    lienzo.fillRect(o118x,o118y,o118anch,o118h);
    lienzo.fillRect(o119x,o119y,o119anch,o119h);
    lienzo.fillRect(o120x,o120y,o120anch,o120h);
    lienzo.fillRect(o121x,o121y,o121anch,o121h);
    lienzo.fillRect(o122x,o122y,o122anch,o122h);
    lienzo.fillRect(o123x,o123y,o123anch,o123h);
    lienzo.fillRect(o124x,o124y,o124anch,o124h);
    lienzo.fillRect(o125x,o125y,o125anch,o125h);
    lienzo.fillRect(o126x,o126y,o126anch,o126h);
    lienzo.fillRect(o127x,o127y,o127anch,o127h);
    lienzo.fillRect(o128x,o128y,o128anch,o128h);
    lienzo.fillRect(o129x,o129y,o129anch,o129h);
    lienzo.fillRect(o130x,o130y,o130anch,o130h);
    lienzo.fillRect(o131x,o131y,o131anch,o131h);
    lienzo.fillRect(o132x,o132y,o132anch,o132h);
    lienzo.fillRect(o133x,o133y,o133anch,o133h);
    lienzo.fillRect(o134x,o134y,o134anch,o134h);
    lienzo.fillRect(o135x,o135y,o135anch,o135h);
    lienzo.fillRect(o136x,o136y,o136anch,o136h);
    lienzo.fillRect(o137x,o137y,o137anch,o137h);
    lienzo.fillRect(o138x,o138y,o138anch,o138h);
    lienzo.fillRect(o139x,o139y,o139anch,o139h);
    lienzo.fillRect(o140x,o140y,o140anch,o140h);
    lienzo.fillRect(o141x,o141y,o141anch,o141h);
    lienzo.fillRect(o142x,o142y,o142anch,o142h);
    lienzo.fillRect(o143x,o143y,o143anch,o143h);
    lienzo.fillRect(o144x,o144y,o144anch,o144h);
    lienzo.fillRect(o145x,o145y,o145anch,o145h);
    lienzo.fillRect(o146x,o146y,o146anch,o146h);
    lienzo.fillRect(o147x,o147y,o147anch,o147h);
    lienzo.fillRect(o148x,o148y,o148anch,o148h);
    lienzo.fillRect(o149x,o149y,o149anch,o149h);
    lienzo.fillRect(o150x,o150y,o150anch,o150h);
    lienzo.fillRect(o151x,o151y,o151anch,o151h);
    lienzo.fillRect(o152x,o152y,o152anch,o152h);
    lienzo.fillRect(o153x,o153y,o153anch,o153h);
    lienzo.fillRect(o154x,o154y,o154anch,o154h);
    lienzo.fillRect(o155x,o155y,o155anch,o155h);
    lienzo.fillRect(o156x,o156y,o156anch,o156h);
    lienzo.fillRect(o157x,o157y,o157anch,o157h);
    lienzo.fillRect(o158x,o158y,o158anch,o158h);
    lienzo.fillRect(o159x,o159y,o159anch,o159h);
    lienzo.fillRect(o160x,o160y,o160anch,o160h);
    lienzo.fillRect(o161x,o161y,o161anch,o161h);
    lienzo.fillRect(o162x,o162y,o162anch,o162h);
    lienzo.fillRect(o163x,o163y,o163anch,o163h);
    lienzo.fillRect(o164x,o164y,o164anch,o164h);
    lienzo.fillRect(o165x,o165y,o165anch,o165h);
    lienzo.fillRect(o166x,o166y,o166anch,o166h);
    lienzo.fillRect(o167x,o167y,o167anch,o167h);
    lienzo.fillRect(o168x,o168y,o168anch,o168h);
    lienzo.fillRect(o169x,o169y,o169anch,o169h);
    lienzo.fillRect(o170x,o170y,o170anch,o170h);
    lienzo.fillRect(o171x,o171y,o171anch,o171h);
    lienzo.fillRect(o172x,o172y,o172anch,o172h);
    lienzo.fillRect(o173x,o173y,o173anch,o173h);
    lienzo.fillRect(o174x,o174y,o174anch,o174h);
    lienzo.fillRect(o175x,o175y,o175anch,o175h);
    lienzo.fillRect(o176x,o176y,o176anch,o176h);
    lienzo.fillRect(o177x,o177y,o177anch,o177h);
    lienzo.fillRect(o178x,o178y,o178anch,o178h);
    lienzo.fillRect(o179x,o179y,o179anch,o179h);
    lienzo.fillRect(o180x,o180y,o180anch,o180h);
    lienzo.fillRect(o181x,o181y,o181anch,o181h);
    lienzo.fillRect(o182x,o182y,o182anch,o182h);
    lienzo.fillRect(o183x,o183y,o183anch,o183h);
    lienzo.fillRect(o184x,o184y,o184anch,o184h);
    lienzo.fillRect(o185x,o185y,o185anch,o185h);
    lienzo.fillRect(o186x,o186y,o186anch,o186h);
    lienzo.fillRect(o187x,o187y,o187anch,o187h);
    lienzo.fillRect(o188x,o188y,o188anch,o188h);
    lienzo.fillRect(o189x,o189y,o189anch,o189h);
    lienzo.fillRect(o190x,o190y,o190anch,o190h);
    lienzo.fillRect(o191x,o191y,o191anch,o191h);
    lienzo.fillRect(o192x,o192y,o192anch,o192h);
    lienzo.fillRect(o193x,o193y,o193anch,o193h);
    lienzo.fillRect(o194x,o194y,o194anch,o194h);
    lienzo.fillRect(o195x,o195y,o195anch,o195h);
    lienzo.fillRect(o196x,o196y,o196anch,o196h);
    lienzo.fillRect(o197x,o197y,o197anch,o197h);
    lienzo.fillRect(o198x,o198y,o198anch,o198h);
    lienzo.fillRect(o199x,o199y,o199anch,o199h);
    lienzo.fillRect(o200x,o200y,o200anch,o200h);
    lienzo.fillRect(o201x,o201y,o201anch,o201h);
    lienzo.fillRect(o202x,o202y,o202anch,o202h);
    lienzo.fillRect(o203x,o203y,o203anch,o203h);
    lienzo.fillRect(o204x,o204y,o204anch,o204h);
    lienzo.fillRect(o205x,o205y,o205anch,o205h);
    lienzo.fillRect(o206x,o206y,o206anch,o206h);
    lienzo.fillRect(o207x,o207y,o207anch,o207h);
    lienzo.fillRect(o208x,o208y,o208anch,o208h);
    lienzo.fillRect(o209x,o209y,o209anch,o209h);
    lienzo.fillRect(o210x,o210y,o210anch,o210h);
    lienzo.fillRect(o211x,o211y,o211anch,o211h);
    lienzo.fillRect(o212x,o212y,o212anch,o212h);
    lienzo.fillRect(o213x,o213y,o213anch,o213h);
    lienzo.fillRect(o214x,o214y,o214anch,o214h);
    lienzo.fillRect(o215x,o215y,o215anch,o215h);
    lienzo.fillRect(o216x,o216y,o216anch,o216h);
    lienzo.fillRect(o217x,o217y,o217anch,o217h);
    lienzo.fillRect(o218x,o218y,o218anch,o218h);
    lienzo.fillRect(o219x,o219y,o219anch,o219h);
    lienzo.fillRect(o220x,o220y,o220anch,o220h);
    lienzo.fillRect(o221x,o221y,o221anch,o221h);
    lienzo.fillRect(o222x,o222y,o222anch,o222h);
    lienzo.fillRect(o223x,o223y,o223anch,o223h);
    lienzo.fillRect(o224x,o224y,o224anch,o224h);
    lienzo.fillRect(o225x,o225y,o225anch,o225h);
    lienzo.fillRect(o226x,o226y,o226anch,o226h);
    lienzo.fillRect(o227x,o227y,o227anch,o227h);
    lienzo.fillRect(o228x,o288y,o228anch,o228h);
    lienzo.fillRect(o229x,o229y,o229anch,o229h);
    lienzo.fillRect(o230x,o230y,o230anch,o230h);
    lienzo.fillRect(o231x,o231y,o231anch,o231h);
    lienzo.fillRect(o232x,o232y,o232anch,o232h);
    lienzo.fillRect(o233x,o233y,o233anch,o233h);
    lienzo.fillRect(o234x,o234y,o234anch,o234h);
    lienzo.fillRect(o235x,o235y,o235anch,o235h);
    lienzo.fillRect(o236x,o236y,o236anch,o236h);
    lienzo.fillRect(o237x,o237y,o237anch,o237h);
    lienzo.fillRect(o238x,o238y,o238anch,o238h);
    lienzo.fillRect(o239x,o239y,o239anch,o239h);
    lienzo.fillRect(o240x,o240y,o240anch,o240h);
    lienzo.fillRect(o241x,o241y,o241anch,o241h);
    lienzo.fillRect(o242x,o242y,o242anch,o242h);
    lienzo.fillRect(o243x,o243y,o243anch,o243h);
    lienzo.fillRect(o244x,o244y,o244anch,o244h);
    lienzo.fillRect(o245x,o245y,o245anch,o245h);
    lienzo.fillRect(o246x,o246y,o246anch,o246h);
    lienzo.fillRect(o247x,o247y,o247anch,o247h);
    lienzo.fillRect(o248x,o248y,o248anch,o248h);
    lienzo.fillRect(o249x,o249y,o249anch,o249h);
    lienzo.fillRect(o250x,o250y,o250anch,o250h);
    lienzo.fillRect(o251x,o251y,o251anch,o251h);
    lienzo.fillRect(o252x,o252y,o252anch,o252h);
    lienzo.fillRect(o253x,o253y,o253anch,o253h);
    lienzo.fillRect(o254x,o254y,o254anch,o254h);
    lienzo.fillRect(o255x,o255y,o255anch,o255h);
    lienzo.fillRect(o256x,o256y,o256anch,o256h);
    lienzo.fillRect(o257x,o257y,o257anch,o257h);
    lienzo.fillRect(o258x,o258y,o258anch,o258h);
    lienzo.fillRect(o259x,o259y,o259anch,o259h);
    lienzo.fillRect(o260x,o260y,o260anch,o260h);
    lienzo.fillRect(o261x,o261y,o261anch,o261h);
    lienzo.fillRect(o262x,o262y,o262anch,o262h);
    lienzo.fillRect(o263x,o263y,o263anch,o263h);
    lienzo.fillRect(o264x,o264y,o264anch,o264h);
    lienzo.fillRect(o265x,o265y,o265anch,o265h);
    lienzo.fillRect(o266x,o266y,o266anch,o266h);
    lienzo.fillRect(o267x,o267y,o267anch,o267h);
    lienzo.fillRect(o268x,o268y,o268anch,o268h);
    lienzo.fillRect(o269x,o269y,o269anch,o269h);
    lienzo.fillRect(o270x,o270y,o270anch,o270h);
    lienzo.fillRect(o271x,o271y,o271anch,o271h);
    lienzo.fillRect(o272x,o272y,o272anch,o272h);
    lienzo.fillRect(o273x,o273y,o273anch,o273h);
    lienzo.fillRect(o274x,o274y,o274anch,o274h);
    lienzo.fillRect(o275x,o275y,o275anch,o275h);
    lienzo.fillRect(o276x,o276y,o276anch,o276h);
    lienzo.fillRect(o277x,o277y,o277anch,o277h);
    lienzo.fillRect(o278x,o278y,o278anch,o278h);
    lienzo.fillRect(o279x,o279y,o279anch,o279h);
    lienzo.fillRect(o280x,o280y,o280anch,o280h);
    lienzo.fillRect(o281x,o281y,o281anch,o281h);
    lienzo.fillRect(o282x,o282y,o282anch,o282h);
    lienzo.fillRect(o283x,o283y,o283anch,o283h);
    lienzo.fillRect(o284x,o284y,o284anch,o284h);
    lienzo.fillRect(o285x,o285y,o285anch,o285h);
    lienzo.fillRect(o286x,o286y,o286anch,o286h);
    lienzo.fillRect(o287x,o287y,o287anch,o287h);
    lienzo.fillRect(o288x,o288y,o288anch,o288h);
    lienzo.fillRect(o289x,o289y,o289anch,o289h);
    lienzo.fillRect(o290x,o290y,o290anch,o290h);
    lienzo.fillRect(o291x,o291y,o291anch,o291h);
    lienzo.fillRect(o292x,o292y,o292anch,o292h);
    lienzo.fillRect(o293x,o293y,o293anch,o293h);
    lienzo.fillRect(o294x,o294y,o294anch,o294h);
    lienzo.fillRect(o295x,o295y,o295anch,o295h);
    lienzo.fillRect(o296x,o296y,o296anch,o296h);
    lienzo.fillRect(o297x,o297y,o297anch,o297h);
    lienzo.fillRect(o298x,o298y,o298anch,o298h);
    lienzo.fillRect(o299x,o299y,o299anch,o299h);
    lienzo.fillRect(o300x,o300y,o300anch,o300h);
    lienzo.stroke();
    lienzo.closePath();
    
}

function loop(datos){//loops para actualizar el canvas. (funcion principal)
    while (true){
	console.log("puto el que lo lea");
	draw();
    }
}
